### ISSUE TITLE
Bad link to the Udacity API in the API Inspiration lesson

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#1]
Link to lesson: https://classroom.udacity.com/nanodegrees/nd001/parts/e87c34bf-a9c0-415f-b007-c2c2d7eead73/modules/271165859175460/lessons/3174548544/concepts/31806585900923

Link to Udacity API gets a 404 error

**Comment by richardkalehoff** [comment]
Thanks, Sarah! I've updated the link to the correct URL: https://www.udacity.com/public-api/v1/courses

**Comment by sarah-maris** [comment]
Hey Richard -- found another spot with the same bad link.  It's in the APIs lesson of the Asynchronous JavaScript course:  https://classroom.udacity.com/courses/ud109/lessons/8cb1042e-3260-469c-9f78-8e2f092a4725/concepts/85c71db9-5c28-4978-97aa-d54584e987ea

**Comment by richardkalehoff** [comment]
Thanks, again! I've updated the link in Asynchronous JavaScript, too!
