### ISSUE TITLE
Broken link in Website Ops lesson

### ISSUE THREAD

**Issue by uncleoptimus** [udacity/fend-issues#10]
https://classroom.udacity.com/nanodegrees/nd001/parts/e87c34bf-a9c0-415f-b007-c2c2d7eead73/modules/273584856175461/lessons/4138328558/concepts/41536885560923

CSSTriggers link needs to be updated to this:
https://aerotwist.com/blog/css-triggers/

as brought up in this forum thread:
https://discussions.udacity.com/t/identifying-jank-sample/302726/4

**Comment by richardkalehoff** [comment]
Thanks! It looks like Paul Lewis/Google moved the project to https://csstriggers.com/

I've updated it in the course. Thanks, again!
