### ISSUE TITLE
Says "Click Skip to Quiz" instead of "Click Start Quiz"

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#107]
https://classroom.udacity.com/nanodegrees/nd001/parts/0a11a6d9-a730-4f9b-ad79-035d1e46c3f3/modules/4d4626ff-de39-4af7-9cf1-a26774ee022c/lessons/7222405183/concepts/72315435530923

HTML Syntax, Lesson 5: Problem set

In almost all assignments you have the instruction "Skip to quiz" but the content of the link you are referring to is "Start Quiz". Not a big issue to deal with, but it's should feel better if it would be the same reference.

**Comment by hbkwong** [comment]
Clearing out old issues. The entire quiz has been replaced by a Workspace! Thanks again Jess
