### ISSUE TITLE
Web Programming with JS - 2.5 Style Guide Link

### ISSUE THREAD

**Issue by kellim** [udacity/fend-issues#109]
In Web Programming with JavaScript Lesson 2: Data Types & Variables: 5. Strings - under the tip, there's a link with the text "JavaScript Udacity style guide" and I'm not sure if you are linking to the GitHub repo on purpose, but I think it would be less confusing to link directly to the JavaScript tab of the Udacity Frontend Nanodegree Style Guide.

Current link: https://github.com/udacity/frontend-nanodegree-styleguide

Suggested link: http://udacity.github.io/frontend-nanodegree-styleguide/javascript.html

Link: https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/cd56eea9-99b5-40c8-8725-a66a651e1ff0/lessons/74007e2e-2a0a-4de3-a8a6-5c2ec4275773/concepts/a7e05a9a-b9af-40c9-b917-541c93ebf414
http://udacity.github.io/frontend-nanodegree-styleguide/javascript.html

**Comment by hbkwong** [comment]
Agreed. Thank you for the incredible amount of detail in this post, @kellim. Having all those links really helped streamline resolution! If you don't see the fix live by the time you read this, let me know. Otherwise, we're good to go!
