### ISSUE TITLE
Web Programming with JS - 2.7 reassigning a variable to a value

### ISSUE THREAD

**Issue by kellim** [udacity/fend-issues#110]
In Web Programming with JavaScript Lesson 2: Data Types & Variables: 7. Variables, in the lesson text under the video it says "You can also change the start of the greeting by reassigning the variable greeting to a new string value."

I think this is wrong because you don't assign a variable to a string value - it's should be the other way around. 

How about changing it to this?:

"You can also change the start of the greeting by reassigning a new string value to the variable greeting."

**Comment by hbkwong** [comment]
I agree. We assign a _value_ to a variable. You should see the update soon! Thanks again @kellim
