### ISSUE TITLE
Super and Extends Typo

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#111]
https://classroom.udacity.com/nanodegrees/nd001/parts/9e34624d-cdc8-4cd7-9d7e-78943413e645/modules/2fc0e696-4879-47f6-afeb-48730cd8fb1e/lessons/3925704a-be38-4b70-8c8b-a4a812b6a309/concepts/6b91f1d9-e0e0-43b7-815f-1a9a47b78a1d

(Version 6.0)

Just wanted to point out a possible typo. On the Front End Developer program, lesson 17, section 17 it looks like the logical OR ( || ) operator is being used instead of the assignment operator ( = ). 
Is that intentional? If that's correct it seemed to come out of nowhere.

Ticket #682282

**Comment by veronikabenkeser** [comment]
This was a bug for a different reason: If the passed in argument was 0, that value (and not the default value) should be used, so we shouldn't have the logical OR operator in this assignment. The code has been fixed.
