### ISSUE TITLE
Prototypal Inheritance Typo in Code

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#112]
https://classroom.udacity.com/nanodegrees/nd001/parts/4942f4d7-a48d-4794-9eb0-404b3ed3cfe1/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/7a95cd0f-752d-422e-b5a4-af8ddeaca0aa/concepts/ab0184cb-2341-4ece-91f9-8c1a971769d0#

(Version 7.0)

I am currently doing the FEND and I noticed a mistake in the code example in Part 3 of the FEND --> Lesson 9: Classes and Objects --> 5. Prototypal Inheritance. The text refers to a method called "sayName" but in the code example the method is named "meow".

Ticket #681683

**Comment by hbkwong** [comment]
Fixed! Thank you @JessicaBettencourt
