### ISSUE TITLE
JQuery and $ Doesn't Work on European Site

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#115]
https://classroom.udacity.com/courses/ud304-emea/lessons/3314378535/concepts/33166386840923

"We are guided to open JavaScript console on udacity.com, then type 'jQuery' and '$'. I am redirected to eu.udacity.com. When I write 'jQuery' and '$' into the JavaScript console, it returns: Undefined. Also, for <code>listElements = $("li");</code> or <code>listElements = jQuery('li'); </code> it returns: Uncaught TypeError: $ is not a function or Uncaught TypeError: jQuery is not a function. It seems they do not work on the European Udacity page, unless you change the country to United States, from the bottom of the page."

Ticket #704496

**Comment by hbkwong** [comment]
Clearing out old tickets. This is a deprecated course in an older version of FEND. No more jQuery! @JessicaBettencourt
