### ISSUE TITLE
Lesson 20.3 - fix markdown link

### ISSUE THREAD

**Issue by kellim** [udacity/fend-issues#116]
Link: https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/39d760cf-9593-420d-9a97-57bff31e29c1/concepts/8cd9dd1c-8347-4e28-ae80-a7cecb48fd00

The markdown for the link has a )
 instead of [  at the end of createElement docs so the link isn't showing up properly.

It's under Question 3 of 4 as

Here's the .createElement() documentation page on MDN: [createElement docs)(https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement)

**Comment by kellim** [comment]
Oops, I mean the markdown for the link has a ) instead of a ]

**Comment by hbkwong** [comment]
Fixed! @kellim
