### ISSUE TITLE
Lesson 20.4 - fix markdown link

### ISSUE THREAD

**Issue by kellim** [udacity/fend-issues#117]
https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/39d760cf-9593-420d-9a97-57bff31e29c1/concepts/6471805e-c4a8-4ed7-8efc-16ba0acbc2c8

Under Removing a Child Element, this link is not formatted properly:

[removeChild docs)(https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild)

The link should be [removeChild docs](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild)

**Comment by kellim** [comment]
It shows a link instead of the code here since this uses markdown formatting. :)

It should be `[removeChild docs](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild)`

**Comment by hbkwong** [comment]
Good to go! @kellim
