### ISSUE TITLE
Lesson 2-20-4 - "following" should be "preceding"

### ISSUE THREAD

**Issue by kellim** [udacity/fend-issues#118]
https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/39d760cf-9593-420d-9a97-57bff31e29c1/concepts/6471805e-c4a8-4ed7-8efc-16ba0acbc2c8

Under the "A drawback (and workaround!) with the .removeChild() Method" heading, after it says "Let's walk through this code."

It has this code block: 
```
const mainHeading = document.querySelector('h1');
```

And the text that's after it refers to the code block as the following code:
"The following code will select the first \<h1\> on the page and stores it in the mainHeading variable. Now to the next line:"

There's code that follows the statement about the following code but it's got different explanation text below it.

**Comment by hbkwong** [comment]
Agreed and fixed! Thanks for being so thorough @kellim
