### ISSUE TITLE
Lesson 2-20-5 typo issues

### ISSUE THREAD

**Issue by kellim** [udacity/fend-issues#120]
https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/39d760cf-9593-420d-9a97-57bff31e29c1/concepts/3734dc32-5300-4ad9-96a8-be488f96a180

Issue 1:
Under the heading "Modifying an Element's Style Attribute" it says "Work trying to style an element, the most-specific rules..." 

It looks like it should be "When trying to style..." instead.

Issue 2:
Under the "`.setAttribute()` Is Not Just For Styling" heading, above the video there's a `/` after the word immediately that looks out of place.

**Comment by hbkwong** [comment]
Fixed! You are a boss @kellim. Much appreciated 👍
