### ISSUE TITLE
Lesson 2-21-3 typo/issues

### ISSUE THREAD

**Issue by kellim** [udacity/fend-issues#121]
https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/f270dbcf-eb43-4ce3-b7be-a74d26023496/concepts/5cb73a2b-6509-45a2-88df-d88b3e811d3d

ISSUE 1:
Under the "Removing an Event Listener" heading, the second paragraph says 

"(The newest version of the .addEventListener() specification does have allow for an object to be passed as a third parameter."

This would sound better without the word "have" before "allow".

ISSUE 2:
Question 1 of 4 says "Is the following equality test result in true or false?"

It would sound better as "Will the following..." instead of "Is the following..."

**Comment by hbkwong** [comment]
Fixed! Thanks for reporting these @kellim
