### ISSUE TITLE
Lesson 2-21-4 typo/issues

### ISSUE THREAD

**Issue by kellim** [udacity/fend-issues#122]
Lesson 2-21-4 Typo/Issues

https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/f270dbcf-eb43-4ce3-b7be-a74d26023496/concepts/5fdd280f-9bf8-4c13-b544-24cd9a4fb63e

1st Issue:

Under the "Event Phases Heading" in text under the video it says "Up until this point, we've only see the .addEventListener() method called with two arguments..." 

I think "see" should be "seen" so it reads "...we've only seen..." instead of "...we've only see..."

2nd Issue:
Under the Heading "The Default action" the second sentence seems to be missing a word where it says "However, one incredibly common that professionals use the event object for..." 

It looks like there should be a word between common and that like "thing"
For instance: "However, one incredibly common thing that professionals use the event object for..."

**Comment by hbkwong** [comment]
Thanks @kellim. I added "reason" as the missing word.
