### ISSUE TITLE
Phases of an Event Bug

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#123]
https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/f270dbcf-eb43-4ce3-b7be-a74d26023496/concepts/5fdd280f-9bf8-4c13-b544-24cd9a4fb63e

Just wanted to let you know there's a small typo in Lesson 4 section for of the Front End Nano Degree, Web Programming with Javascript Module. 

Code shows as: 
const links = document.querySelector('a'); 
const thirdLink = items[2]; 
Should be

const links = document.querySelector('a'); 
const thirdLink = links[2];

**Comment by hbkwong** [comment]
@JessicaBettencourt  Fixed! In the classroom and in the scripts.

**Comment by JessicaBettencourt** [comment]
Thank you!
