### ISSUE TITLE
Quiz: Using Let and Const (1-1)

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/fend-issues#125]
[Quiz Link](https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/4116dc31-6d06-4774-b082-d60ca0980d2b/lessons/42383e89-ac6a-491a-b7d0-198851287bbe/concepts/7c8e752b-d552-4bad-ad3f-0f5f263d5dc9)

Following error is being shown on submitting the quiz.

```
File "<string>", line 77, in main
  TypeError: 'NoneType' object has no attribute '__getitem__'
  Environment: {'executor_result': None, 'grade_result': {'comment': 'Thank you for your submission!', 'feedback': '', 'completed': None, 'test_results': [], 'bin_codes': [], 'correct': False}, 'executor_status': None}
  Submission: {'_operation': 'REGRADE', u'StudentMain.js': u'/*\n * Programming Quiz: Using Let and Const (1-1)\n */\n\nconst CHARACTER_LIMIT = 255;\nconst posts = [\n\t"#DeepLearning transforms everything from self-driving cars to language translations. AND it\'s our new Nanodegree!",\n\t"Within your first week of the VR Developer Nanodegree Program, you\'ll make your own virtual reality app",\n\t"I just finished @udacity\'s Front-End Web Developer Nanodegree. Check it out!"\n];\n\n// prints posts to the console\nfunction displayPosts() {\n\tfor (let i = 0; i < posts.length; i++) {\n\t\tconsole.log(posts[i].slice(0, CHARACTER_LIMIT));\n\t}\n}\n\ndisplayPosts();\n'}
```

**Comment by aviaryan** [comment]
I am getting this report from several students as well. It would be great to have it fixed quickly.

**Comment by sarah-maris** [comment]
Confirming this.  The solution that worked previously no longer works.

**Comment by JessicaBettencourt** [comment]
https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/4116dc31-6d06-4774-b082-d60ca0980d2b/lessons/42383e89-ac6a-491a-b7d0-198851287bbe/concepts/7c8e752b-d552-4bad-ad3f-0f5f263d5dc9

**Comment by karlud** [comment]
This was a configuration problem in our quiz evaluation system. Fixed.
