### ISSUE TITLE
403 Error HTML Style Guide

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#131]
Students are getting 403 error while trying to download HTML, CSS, and Javascript Style Guide from Resources tab. A large number of students are reporting this issue.

**Comment by MoElwekil** [comment]
can you provide us with the URL please so everyone can check it?
Thanks

**Comment by Barmalew** [comment]
Here :) https://www.udacity.com/api/nodes/nd001/supplemental_media/html-css-and-javascript-style-guidepdf/download

**Comment by hbkwong** [comment]
Should be good to go! I replaced the original file with a new upload. If it continues to be an issue, feel free to reopen the issue or message me directly. Thanks for reporting, everyone
