### ISSUE TITLE
"Skip the Quiz" vs "Start Quiz"

### ISSUE THREAD

**Issue by towmass** [udacity/fend-issues#134]
There is the last line of text in Lesson5-9 Quiz: Add an Image and instruction says "Click "Skip to Quiz" when you're ready to go!" but the link below is called "Start Quiz".
Link: https://classroom.udacity.com/nanodegrees/nd001/parts/0a11a6d9-a730-4f9b-ad79-035d1e46c3f3/modules/4d4626ff-de39-4af7-9cf1-a26774ee022c/lessons/7222405183/concepts/73054287010923

**Comment by hbkwong** [comment]
This quiz used a deprecated format, and has since been updated with a Workspace. Thanks for reporting, @towmass!
