### ISSUE TITLE
Given article not found

### ISSUE THREAD

**Issue by towmass** [udacity/fend-issues#137]
The article about iOS debugging tools probably does not exist anymore:
https://classroom.udacity.com/nanodegrees/nd001/parts/0a11a6d9-a730-4f9b-ad79-035d1e46c3f3/modules/afa5ca8b-f8dc-4160-83ff-3e5ccc2e1972/lessons/3ecd9f0c-a731-4a38-95b9-95a95febf7b2/concepts/4222787770923

Link in the lesson: https://www.smashingmagazine.com/2014/09/testing-mobile-emulators-simulators-remote-debugging/2/

**Comment by hbkwong** [comment]
Fixed! Thanks for reporting this one, @towmass
