### ISSUE TITLE
Wrong instructions for downloadable content

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#139]
https://classroom.udacity.com/nanodegrees/nd001/parts/0a11a6d9-a730-4f9b-ad79-035d1e46c3f3/modules/273669854375463/lessons/2736698543239847/concepts/26558985860923

Instructions:

Download the design mockup file from the Downloadables section (in the lower right hand corner of your screen, just below this text) and review it.

This should say lower "left" hand corner.

**Comment by hbkwong** [comment]
Fixed! I removed any left or right indications in the instructions just in case our classroom is updated again lol. Thanks again @JessicaBettencourt
