### ISSUE TITLE
Change Udacity quizzes that use the feedback tool to ask for "codeword" or "password" instead of "code"

### ISSUE THREAD

**Issue by SittingFox** [udacity/fend-issues#14]
The quizzes that make use of the feedback tool request that the students enter the "code". Some students get confused and think that means to put in their entire written code.

I think simply adjusting the word in each of the quizzes would do wonders. "Codeword" or "password" would be so much clearer.

**Comment by abustamam** [comment]
I agree, I am getting a few students having tons of trouble on quizzes.

**Comment by richardkalehoff** [comment]
We are working on a replacement to the Udacity Feedback Extension. Once it is completed we will update FEND by swapping out quizzes that depend on the extension with the new tool.
