### ISSUE TITLE
Syntax errors, sub optimal recommendation in js style guide.

### ISSUE THREAD

**Issue by 71emj** [udacity/fend-issues#145]

**Comment by 71emj** [comment]
Okay, I messed up didn't write anything before open it. So I will write the stuff in the comment

**Comment by 71emj** [comment]
In the JS style guide there are several places when using for loop, for-in loop, the iterator "i" is declared as const instead of let or var.

**Comment by 71emj** [comment]
In regarding to sub optimal recommendation, an example would be with the for-in loop http://udacity.github.io/frontend-nanodegree-styleguide/javascript.html#for-in-loop .

The style guide clearly prefered declarative javascript or imperative, but the recommendation given is not so (and unneccessary verbose). 

In the style guide we see this snippets as solution:
```js
myObj = {'firstName':'Ada','lastName':'Lovelace'};
for (const key in myObj) {
    if (myObj.hasOwnProperty(key)) {
        console.log(myObj[key]);
    }
}
```
Not only does it add an additional layer of code, it makes it unclear and hard to comprehend.

A better solution would probably be something like this:
```js
myObj = {'firstName':'Ada','lastName':'Lovelace'};
Object.entries(myObj).forEach( item => console.log( item[1] ) );
```

**Comment by hbkwong** [comment]
Hi @71emj, thanks for your two cents on this! Feel free to submit a PR and I'll make sure this gets reviewed as we maintain the front-end style guide: https://github.com/udacity/frontend-nanodegree-styleguide
