### ISSUE TITLE
Clarify Output JuliaJames

### ISSUE THREAD

**Issue by SittingFox** [udacity/fend-issues#146]
Lesson 4: Loops
Quiz 4-1

I have a student complaining about lack of clarity in the instructions. They seem to believe the use of only `if` statements, and the order being presented, is terribly misleading.

I think it would be a good idea to add hints to better communicate the idea. For instance, say that only 1 thing should be output each time. It also may be worth hinting at `if`/`else`.

https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/cd56eea9-99b5-40c8-8725-a66a651e1ff0/lessons/1234cec0-179b-40b6-9435-f10263c7de33/concepts/2a571380-d3dc-4acb-98a1-96766e6d5436

**Comment by veronikabenkeser** [comment]
Thank you for sharing your mentee's experience! I took a look at the question and the instructions, and I think they're clear as to what needs to be done. I think the student may have misinterpreted the instructions. I think that adding additional hints will just give students the answer.
