### ISSUE TITLE
Clarify Ellipse Symbols

### ISSUE THREAD

**Issue by SittingFox** [udacity/fend-issues#147]
Lesson 4: Loops
Quiz 4-2

Students can be confused by the difference between the regularly-written ellipse and the special character. They may also confusingly think there needs to be spaces, when comparing the two.

I suggest saying it needs to be written as 3 periods in a row, not the lone special character.

https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/cd56eea9-99b5-40c8-8725-a66a651e1ff0/lessons/1234cec0-179b-40b6-9435-f10263c7de33/concepts/d150e73c-6439-461e-b52b-87c6e5c1ea3a

**Comment by hbkwong** [comment]
Fixed! Made it extra clear to use three _consecutive_ periods rather than the special ellipses character. Thank you for the suggestion, @SittingFox
