### ISSUE TITLE
Lesson 3.7.4 Beware of Globals - broken link

### ISSUE THREAD

**Issue by Soheevich** [udacity/fend-issues#150]
"Coupling on Wikipedia" link is broken. The right one is: https://en.wikipedia.org/wiki/Coupling_(computer_programming)

**Comment by veronikabenkeser** [comment]
Thank you for letting us know! Fixed.

**Comment by hbkwong** [comment]
Markdown didn't like the closing parenthesis in the link, so I wrapped it with a bitly link. The update is live in the classroom. Thanks for reporting, @Soheevich!
