### ISSUE TITLE
Lesson 4.6.2 jQuery's `ajax()` Method

### ISSUE THREAD

**Issue by Calexxxxx** [udacity/fend-issues#153]
**Making an Ajax call**

jQuery's .ajax() method has to be incredibly versatile and powerful if it's what powers all of jQuery's asynchronous requests. A simple Ajax request would look like this:

```
$.ajax({
    url: 'http://swapi.co/api/people/1/'
});
```

Gives a CORS error the correct URL should be `https://swapi.co/api/people/1/` 

The same URL is also used in 4.6.3

**Comment by veronikabenkeser** [comment]
Thank you for flagging! Fixed.
