### ISSUE TITLE
Setting Our Own 'this' quiz possible bug

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#155]
https://classroom.udacity.com/nanodegrees/nd001/parts/4942f4d7-a48d-4794-9eb0-404b3ed3cfe1/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/7a95cd0f-752d-422e-b5a4-af8ddeaca0aa/concepts/f55148aa-4cb0-423a-8589-e85d99535919

Hi, Quiz in section 3 'Exploring JS - Objects, Tools and Testing' , lesson 9 'Classes and objects', point 4 'Setting Our Own `this'' is working badly ...

Here is code of this quize: 
// 
const driver = { 
name: 'Danica', 
displayName: function () { 
console.log(`Name: ${this.name}`); 
} 
};

const car = { 
name: 'Fusion' 
};

//

Any of good answers which are working in console in Chrome isn't accepted.

First good answer: 
// 
const displayNameCar = driver.displayName; 
const boundFunction = displayNameCar.bind(car); 
boundFunction(); 
//

Second good answer: 
// 
const displayNameCar = driver.displayName.bind(car); 
displayNameCar(); 
//

Could you fix this, thanks!

**Comment by hbkwong** [comment]
Resolved in https://github.com/udacity/fend-issues/issues/140
