### ISSUE TITLE
Students are confused by instructions for Quiz: I Got Bills (6-9)

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#16]
The instructions do not make it clear that the revised bill data must be rounded to two decimals.  Instructions for `.toFixed` are noted as  "Tip" -- but  some students have interpreted as optional.

Link to quiz: https://classroom.udacity.com/nanodegrees/nd001/parts/9d3a4440-1e65-4fc5-9ac1-b40e401ad069/modules/cd56eea9-99b5-40c8-8725-a66a651e1ff0/lessons/378e7ff7-f7e5-4487-b5c4-fdf9b5c351d9/concepts/fc5ae6f0-2cf3-4e44-a1dc-4df1e66a7ddb#

**Comment by richardkalehoff** [comment]
Thanks for the info! I have updated the quiz to include detailed instructions. :+t:
