### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#161]
https://classroom.udacity.com/nanodegrees/nd001/parts/a76bb181-979a-4b36-b32f-01bced6e363e/modules/1a745b72-089a-4569-b60f-cab36f3bfe3e/lessons/f270dbcf-eb43-4ce3-b7be-a74d26023496/concepts/5fdd280f-9bf8-4c13-b544-24cd9a4fb63e#recap

It's just above the "Recap" section linked above.

Instead of `document.querySelector('a')` it should be `document.querySelectorAll('a')`.

**Comment by veronikabenkeser** [comment]
Fixed.
