### ISSUE TITLE
Missing `\` to escape character in "The Call Stack" lesson

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#167]
Link to lesson:  https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/364ca3da-1eb9-4213-beb4-7791ac4e1ea4/concepts/da8ce985-9c2a-468f-8337-448adb2beea0

There is an unescaped single quote in one of the statements in the second example:

Current code:
```
    para.textContent = 'Isn't that cool?';

```

Should be:
```
   para.textContent = 'Isn\'t that cool ? ';
```
or 
```
   para.textContent = "Isn't that cool ?";
```

**Comment by veronikabenkeser** [comment]
Thank you for flagging! Fixed.
