### ISSUE TITLE
Missing ) in event listener in first example in "The Event Loop" lesson

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#168]
Link to lesson: https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/364ca3da-1eb9-4213-beb4-7791ac4e1ea4/concepts/3461277b-4d6e-43d2-af67-e576f7612863

Current code:

```
document.addEventListener('click', function numbers() {
    console.log('123');
};
```

Should be:
```
document.addEventListener('click', function numbers() {
    console.log('123');
});
```

**Comment by veronikabenkeser** [comment]
Thank you for flagging! Fixed.
