### ISSUE TITLE
3.9.5 - question 3 validation message

### ISSUE THREAD

**Issue by dwiehoff** [udacity/fend-issues#178]
"For a closer look at isPrototypeOf() and getPrototypeOf(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf), feel free to check out their MDN pages (linked)."

isPrototypeOf() is linked
getPrototypeOf() was supposed to be as well, I presume

**Comment by hbkwong** [comment]
Incorrect markdown. It has since been fixed! Thanks for reporting this one, @dwiehoff.
