### ISSUE TITLE
Managing Layers 2 - Video missing resource link

### ISSUE THREAD

**Issue by SittingFox** [udacity/fend-issues#18]
[Managing Layers 2](https://classroom.udacity.com/nanodegrees/nd001/parts/e87c34bf-a9c0-415f-b007-c2c2d7eead73/modules/273584856175461/lessons/4129068601/concepts/41395386460923) is missing the link to [the site being used](https://www.html5rocks.com/static/demos/parallax/demo-2/demo.html). Nothing is written in the instructors' notes at all.

Since the page is visibly identical to the previous one, it is easy for students to not realize the URL/page in the video is different. So it might be good to also make clear that the page is a different one.

**Comment by richardkalehoff** [comment]
I've updated the Classroom page with a link to the new demo site. Thanks for posting, Stacy! :raised_hands:
