### ISSUE TITLE
Lesson 4.10.14 - bug in feedback

### ISSUE THREAD

**Issue by hajczek** [udacity/fend-issues#184]
There is an error in box feedback even if every elements from quiz are done in application... The error is with first point: 'legoBuilder script tag exists' - even if the script tag is added on the page ...

**Comment by hajczek** [comment]
![bootstrapquiz-error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab54020e9841f00145908a0/125516c66e82c728ace21e0d46ea9b95379197bb8ef9ae56ad47bd913b5428616b48e13b628ae92dbc56395b4d5a47a9430b0a12f5f8db2fa3b66f708a5e0ebcd56c0c25c32f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e58f8f4c3d1d00118bfe5f27ed.png)

**Comment by hbkwong** [comment]
Thanks for reporting, @hajczek! Chrome extension quizzes should have been updated to Workspaces. If you're still seeing errors, feel free to reach out!
