### ISSUE TITLE
Invalid Link Display Prototypal Inheritance

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#186]
https://classroom.udacity.com/nanodegrees/nd001/parts/4942f4d7-a48d-4794-9eb0-404b3ed3cfe1/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/7a95cd0f-752d-422e-b5a4-af8ddeaca0aa/concepts/ec211dfb-a817-4ff0-ae85-9fec23e3253f

Invalid link display on Question 3 of 5. 

getProtototypeOf)

*Ping me if you need a screenshot. 
-Jess

**Comment by hbkwong** [comment]
Fixed! This was actually in a previous Concept, not the link provided by the student. The update should be live in the classroom now. Thanks @JessicaBettencourt !
