### ISSUE TITLE
Setting Our Own `this`

### ISSUE THREAD

**Issue by iondonescu** [udacity/fend-issues#188]
As it is in the video (photo 1), you should replace, in the  github code, console.log(`${this.message}, ${this.name}`) with console.log(`${message}, ${this.name}`). “message” is not "cat" object’s property. You get undefined, Bailey, if you run the code .
<img width="1336" alt="1" src="https://user-images.githubusercontent.com/19903250/39091950-b01fa110-4608-11e8-94c7-6638bee41e70.png">
<img width="1336" alt="2" src="https://user-images.githubusercontent.com/19903250/39091951-b05231f2-4608-11e8-9f25-3fe4537959e1.png">

**Comment by hbkwong** [comment]
Fixed! Great catch, @iondonescu. There is no `message` in the `cat` object, since `message` is being pulled from the function parameter.
