### ISSUE TITLE
Invoking Object Methods

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#189]
There is a little mistake in one lesson: 
Programa Nanodegree Front-End Web Developer > Exploring JS - Objects, Tools and Testing > Objects in Depth > Invoking Object Methods > Passing Arguments Into Methods.

In the example is shown the following: 
console.log(`My favorite programming language is ${language}`); 
It should be 
console.log('My favorite programming language is ${language}');

So, just change the ` for '

https://classroom.udacity.com/nanodegrees/nd001/parts/4942f4d7-a48d-4794-9eb0-404b3ed3cfe1/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/504843ae-ba16-4573-a859-94da7a7d1dd4/concepts/bd94ce28-164e-4ee5-b2bb-819798f22218

Ticket #780294

**Comment by hbkwong** [comment]
Hey @JessicaBettencourt, thanks for reporting. The back-tick (`) should definitely be used over the single quote (') in this case. Using the single quote would print the entire message as a string (so you'd actually see the dollar sign and curly bracket symbols). 

More info here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Want me to reach out to the student directly? Definitely don't want them to be on the wrong track!

**Comment by JessicaBettencourt** [comment]
Yes please, that would be great. Thank you!

**Comment by hbkwong** [comment]
@JessicaBettencourt  On it!
