### ISSUE TITLE
Neighborhood Map rubric guidance for reviewers requires use of async but defer should also meet project requirements.

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#19]
Using the `defer` attribute will also load Google Maps asynchronously but in the Neighborhood Map rubric - https://review.udacity.com/#!/rubrics/17/view  -- the REVIEWER TIPS states that 
>(The script used to load the API in the HTML should include the async attribute

But using `defer` should also meet the requirement because it also allows the page to continue to load while the script is downloading .  The only difference is that `defer` waits until the page is parsed before continuing while `async` runs the script as soon as it is loaded.

**Comment by forbiddenvoid** [comment]
Done.
