### ISSUE TITLE
New Animal Trading Card Instructions/Grader

### ISSUE THREAD

**Issue by CrystalYungwirth** [udacity/fend-issues#191]
Hi, 
In the new Animal Trading Card lab the instructions say:
![image](https://user-images.githubusercontent.com/38540136/39300449-b891b69e-4919-11e8-805f-9a271a2529bf.png)

card.html starter code comes:
![image](https://user-images.githubusercontent.com/38540136/39300483-da4ac3ca-4919-11e8-86c4-00422ad3ee21.png)

If line 13 is updated to class="animal-info" the grader throws the following error:
![image](https://user-images.githubusercontent.com/38540136/39300416-9935568e-4919-11e8-9d8a-39db7404decc.png)

until line 12 is updated to: 
![image](https://user-images.githubusercontent.com/38540136/39300356-650afa3a-4919-11e8-836a-3645534873c1.png)

**Comment by hbkwong** [comment]
Gonna examine this one more closely. Having an `id` _and_ `class` on the same `div` isn't something I'd typically do. Thanks for reporting it!

**Comment by CrystalYungwirth** [comment]
Thanks! Appreciate everything you do and look in to.
