### ISSUE TITLE
Chrome Extension Link Needs to be Removed

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#196]
https://classroom.udacity.com/nanodegrees/nd001/parts/aabd87fc-6edf-4818-a911-15dfa9cabcb8/modules/afa5ca8b-f8dc-4160-83ff-3e5ccc2e1972/lessons/e4b4d168-03d7-4d93-b7fb-a6dc1c62a25b/concepts/35127989610923

Link is under the video. Thanks!

**Comment by hbkwong** [comment]
Hey @JessicaBettencourt  which section (and version) is this in? Link redirects me to the generic classroom lol. Curious to see if it's just a quick fix or an entire Workspace that needs to be implemented  (to replace the Extension quiz)

**Comment by hbkwong** [comment]
Gotcha, thankfully this is the same page as ticket #784659. Fix is on the roadmap! @JessicaBettencourt

**Comment by hbkwong** [comment]
Done and done! Quiz has been replaced with a Workspace. Original solution still stands (and is provided in `solution.html`)

**Comment by JessicaBettencourt** [comment]
Yay!! Thank you!!!
