### ISSUE TITLE
Javascript Foundations Quizzes

### ISSUE THREAD

**Issue by jakenielson** [udacity/fend-issues#2]

**Comment by jakenielson** [comment]
The quizzes starting in Lesson 8 - Getting Up and Running display the success/pass message regardless of what the student enters in the text box. When the student enters the correct code, a debug message displays.

**Comment by jakenielson** [comment]
![quizBug.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5954249b959d94001f41477b/125516c66e82c728ace21e0d46f9819339a096aecda5fd53b652fa912a5265296b51fa7e2286e62ee61379555a5f1dac415a5a15f8f8da7aa3a42062c80d55b98e30063e937f03a6aa811eb500be2983498db0b58c4ec7e93437aa.png)

**Comment by richardkalehoff** [comment]
Hey Jake, do you have a link to this page you can share here?

**Comment by jakenielson** [comment]
https://classroom.udacity.com/nanodegrees/nd001/parts/9d3a4440-1e65-4fc5-9ac1-b40e401ad069/modules/296281861575460/lessons/2239648539/concepts/25973688610923#

This is the link to the quiz shown in the above screenshot. There are other quizzes with similar issues in this area, so some halo testing may be required. But I've got to get back to studying now =)

**Comment by richardkalehoff** [comment]
We are working on a new, replacement grading system. Once it is completed we will update FEND by swapping out existing quizzes with the new tool.
