### ISSUE TITLE
HTML, CSS, JavaScript Syle Guide

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#200]
HTML, CSS, JavaScript Style Guide in the resources tab of version 8.0 is giving a 403. 

(I know this was fixed, but it isn't working again). Confirmed via impersonation. Thanks for looking into this.

**Comment by hbkwong** [comment]
So odd! Can you Slack me some ID's I can impersonate and investigate? Otherwise, rather than linking to a PDF, I think another solution would be just to link to the GitHub Pages version of the style guide. @JessicaBettencourt

**Comment by hbkwong** [comment]
Closing this one out for now. Haven't really seen it in the student Slack. But if it comes up again via email, feel free to assign the ticket to me (or just Slack me directly!)
