### ISSUE TITLE
media queries not working Lesson 2 CSS Frameworks Quiz 11

### ISSUE THREAD

**Issue by karoldavid** [udacity/fend-issues#21]
add meta viewport tag to quiz assets:

<meta name="viewport" content="width=device-width" />

https://discussions.udacity.com/t/media-queries-not-working-lesson-2-css-frameworks-quiz-11/322794

**Comment by richardkalehoff** [comment]
Karon, can you provide a link to the Classroom page?

**Comment by richardkalehoff** [comment]
I'm closing this ticket for now. When you have the link, feel free to respond to this one or open a new ticket.
