### ISSUE TITLE
Weakmaps- const cannot be reassigned

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#211]
https://classroom.udacity.com/nanodegrees/nd001/parts/4942f4d7-a48d-4794-9eb0-404b3ed3cfe1/modules/ecc53652-c50b-4cf0-8460-0e44bda02c7a/lessons/1b997dce-e2ce-4246-b5ae-d39ca175f887/concepts/ae0439c3-436c-4c2f-ba69-8bfc7f947a6c

Version 7.0

In part 3 lesson 11 particularly in 16.Weakmaps a const variable called book1 was reassigned to null in the lesson text and video. consts cannot be reassigned and the variable should have been let not const

**Comment by hbkwong** [comment]
Added an "erratum" note below the video to make sure students aren't confused. Thanks Jessica!
