### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#212]
https://classroom.udacity.com/nanodegrees/nd001/parts/a76bb181-979a-4b36-b32f-01bced6e363e/modules/1a745b72-089a-4569-b60f-cab36f3bfe3e/lessons/74c2a096-61db-4302-9d65-6b7fa9b8c329/concepts/04d813ef-2bfc-4862-a4cc-38057d2a11c3

Core Curriculum 2, Web Programming with Javascript, Lesson 19, Section 5 - getElementByClassName should be getElementsByClassName

**Comment by hbkwong** [comment]
Fixed! So poetic because that section literally tells readers that it's a common mistake... and then we make that mistake. Thanks @JessicaBettencourt !

**Comment by JessicaBettencourt** [comment]
That's exactly what the student said. Thanks Andrew!
