### ISSUE TITLE
2. Constructor Functions- Capitalization

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#218]
https://classroom.udacity.com/nanodegrees/nd001/parts/c02fda3b-67bf-48d6-a64f-c6960e2d4d79/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/7a95cd0f-752d-422e-b5a4-af8ddeaca0aa/concepts/b1b4a75b-a778-406e-8ab8-45191dc3f8f9

FEND NanoDegree. Lesson 9 "Classes and Objects". 2. Constructor Functions 

Question 4 of 4. In a couple places it refers to "instanceof" and others "instanceOf". Note the capitalization of the "o". Should probably standardize this throughout that lesson.

**Comment by hbkwong** [comment]
Fixed! @JessicaBettencourt

**Comment by JessicaBettencourt** [comment]
TY!
