### ISSUE TITLE
How to Use Git and GitHub Quiz Bug

### ISSUE THREAD

**Issue by jakenielson** [udacity/fend-issues#22]
How to Use Git and GitHub - Lesson 3 - Item 30 - Quiz: Resolving Merge Conflicts produces the following output when passing the quiz:

Good job!

"Your code's output:
28 07 2017 22:50:57.455:WARN [watcher]: Pattern "unit_tests.js" does not match any file.
28 07 2017 22:50:57.498:
 with unlimited concurrency
 28 07 2017 22:50:57.760:"

A link to the issue:
https://classroom.udacity.com/courses/ud775/lessons/2969618657/concepts/29941585530923

**Comment by kisgrigg** [comment]
Hi Jake,

Thank you for your feedback. We have a fix coming very soon for this issue.

Best,

Karen
