### ISSUE TITLE
Bug in front-end nanodegree style guide

### ISSUE THREAD

**Issue by JCherryhomes** [udacity/fend-issues#220]
http://udacity.github.io/frontend-nanodegree-styleguide/javascript.html#for-in-loop

The recommended standard for loop example uses const which will result in an error.

**Comment by JCherryhomes** [comment]
```
for (const indexCount = 0; indexCount < myArray.length; indexCount++) {
    console.log(myArray[indexCount]);
};
```

**Comment by hbkwong** [comment]
Fix in place! Thanks for reporting @JCherryhomes
