### ISSUE TITLE
Ember quiz not working due to a missing dependency.

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#221]
**[The Route and Template Quiz](https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/551811858275460/lessons/7026988599/concepts/70182885640923)**  throws an error on load

![image](https://user-images.githubusercontent.com/6298143/40674009-876a476a-6341-11e8-87d2-fdcb0783e372.png)

Pointing to this code: 

![image 1](https://user-images.githubusercontent.com/6298143/40674008-8759e136-6341-11e8-834f-10499fc7446d.png)

It can be resolved by adding 
```
"ember-inflector": "2.2.0"
```  
to the Dev Dependencies in the package.json file

**Comment by hbkwong** [comment]
Just updated the repo. Ready to rock! Thanks again for everything @sarah-maris
