### ISSUE TITLE
Learn Backbone.js- broken link

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#225]
https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/551811858275460/lessons/7084670183/concepts/70005164560923

Lesson 9: Examine a Framework's Source
1. A Framework's Base Features 

The Learn Backbone.js.course link needs to be replaced.

**Comment by hbkwong** [comment]
Fixed! https://www.udacity.com/course/learn-backbonejs--ud990 is the current link
