### ISSUE TITLE
Broken Link to Git Course Leads to 404

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#226]
https://classroom.udacity.com/nanodegrees/nd001/parts/a76bb181-979a-4b36-b32f-01bced6e363e/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/edde9226-f71c-4a81-a858-4c83e4c7b664/concepts/1ad9f705-8b0e-403e-a903-4a757d8ede17

Probably needs to be https://www.udacity.com/course/version-control-with-git--ud123

See ticket #819455

**Comment by hbkwong** [comment]
Hey @JessicaBettencourt , do you know which course/lesson/concept this was in? Having trouble viewing the link 😶

**Comment by JessicaBettencourt** [comment]
Sorry! Lesson 16 working with remotes 1. Intro

**Comment by JessicaBettencourt** [comment]
Web Programming with JavaScript

**Comment by hbkwong** [comment]
Good to go! Thanks, @JessicaBettencourt
