### ISSUE TITLE
Strange message when passing "Refactoring to Consolidate Code" quiz.

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#23]
In this quiz: https://classroom.udacity.com/nanodegrees/nd001/parts/3692bea4-2632-4ce2-a693-32eafb84dd98/modules/269645859775460/lessons/2794468536/concepts/27044186310923

The "Good Job!" message says this:
>29 07 2017 18:34:13.347:
 with unlimited concurrency
 29 07 2017 18:34:13.591:

Your code passed all tests! Great job!

**Comment by sarah-maris** [comment]
![image](https://user-images.githubusercontent.com/6298143/28747369-1bc0e962-746b-11e7-9295-a1ef954b94c3.png)

**Comment by richardkalehoff** [comment]
We are working on a new tool that will replace this style of quiz . Once it is completed we will update FEND by swapping out these existing quizzes with the new tool.
