### ISSUE TITLE
Inaccurate comment in engine.js file in Classic Arcade Game project

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#24]
One of the comments at the top of engine.js says
>* This engine is available globally via the Engine variable 

But it is not:
```
var Engine = (function(global) {
   // code here
})(this);
```
Link to the repo: https://github.com/udacity/frontend-nanodegree-arcade-game/blob/master/js/engine.js

I can submit this as a pull request if you prefer but it appears that all pull requests are being ignored.

**Comment by forbiddenvoid** [comment]
Fixed
