### ISSUE TITLE
Lesson 11: Ember, 22 Quiz: Component Quiz

### ISSUE THREAD

**Issue by AlgirdasM** [udacity/fend-issues#241]
[https://github.com/udacity/FEF-Quiz-Ember-Component](https://github.com/udacity/FEF-Quiz-Ember-Component) has the same issue as [https://github.com/udacity/fend-issues/issues/221](https://github.com/udacity/fend-issues/issues/221)

Need to update package.json with - `"ember-inflector": "2.2.0"` to resolve it.

**Comment by hbkwong** [comment]
Closing out this old old ticket (#221 has since been resolved). Thanks again @AlgirdasM !
