### ISSUE TITLE
Part 3- Lesson 3.12- Semantic Basics - Writing Semantic HTML Quiz

### ISSUE THREAD

**Issue by gauravsinghaec** [udacity/fend-issues#242]
The Udacity feedback extension is not showing any secret code. How to put the code in quiz box?
![image](https://user-images.githubusercontent.com/15084301/41220455-15b2e198-6d7f-11e8-9326-0a2baa326797.png)

**Comment by hbkwong** [comment]
Thanks for checking in. The Chrome Extension has been deprecated, and is not necessary for this quiz. Feel free to access the code in the provided repo, or in the provide live version.

**Comment by gauravsinghaec** [comment]
Where will I get the code. I changed the div into button but where to get the secret code from? It's really confusing as nowhere mentioned in the Frontend Nanodegree accessibility lesson on how to get it.
