### ISSUE TITLE
Lesson 11: Ember, 25 Quiz: Using Services Quiz

### ISSUE THREAD

**Issue by AlgirdasM** [udacity/fend-issues#243]
[https://github.com/udacity/FEF-Quiz-Ember-Service](https://github.com/udacity/FEF-Quiz-Ember-Service) has the same issue as [https://github.com/udacity/fend-issues/issues/221](https://github.com/udacity/fend-issues/issues/221)

Need to update package.json with - `"ember-inflector": "2.2.0"` to resolve it.

**Comment by hbkwong** [comment]
And this one too. Thanks again!
