### ISSUE TITLE
Typo in code instructions

### ISSUE THREAD

**Issue by zach-col** [udacity/fend-issues#249]
Typo in code instructions.

**Comment by zach-col** [comment]
Typo in lesson : A Full Request

The closing bracket needed for a function is within a comment, the bracket just needs to be moved to next line.

function handleSuccess () { 
  console.log( this.responseText ); 
// the HTML of https://unsplash.com/}

https://classroom.udacity.com/nanodegrees/nd001/parts/b29af831-fa50-4fe9-b30d-ad48476664d1/modules/3cc28649-e29e-4095-8dc9-d7943de84d87/lessons/8cb1042e-3260-469c-9f78-8e2f092a4725/concepts/b097333c-2fc3-43b1-8141-5812fcd4a4a6

**Comment by hbkwong** [comment]
Hey @zach-col, having some trouble viewing the link in question. Do you have the name of the module/course/section that this appears in? Thanks again for reporting this one!

**Comment by zach-col** [comment]
Sure thing @hbkwong

4. Front-End Applications
Lesson 5 Ajax with XHR
9 A Full Request

**Comment by hbkwong** [comment]
Thanks @zach-col! Easy fix. The update should be live in the classroom shortly.
