### ISSUE TITLE
Course Links Give 404

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#258]
https://classroom.udacity.com/nanodegrees/nd001/parts/e4e4c31c-2348-4382-826f-caac197d6f5f/modules/551811858275460/lessons/7084452321/concepts/70929589460923#

Lesson 8 Features of Single Pages Apps
2. How to Be Successful 

All 3 Links Under the Video do not work
-Web Tooling & Autiomation
-JavaScript Design Patterns
-Object-Oriented JavaScript

**Comment by hbkwong** [comment]
Not anymore! Good to go @JessicaBettencourt  :D
