### ISSUE TITLE
Lesson 10: Calc() Quiz not working

### ISSUE THREAD

**Issue by kellim** [udacity/fend-issues#26]
Student reports the Calc() Quiz is not working. After watching the lesson before the quiz, it just skips the quiz and goes to the next lesson.

https://classroom.udacity.com/nanodegrees/nd001/parts/b846fc63-9195-42a1-97a8-f98a99100f32/modules/273669854375462/lessons/3520939843/concepts/37391188270923

**Comment by SittingFox** [comment]
It looks like hitting the Next button moves to the next lesson rather than going to the quiz. If you hit the little "Start Quiz" link, you're fine--but I'm pretty sure this was better organized before. That link is easy to miss.
