### ISSUE TITLE
4.2.22 Broken Link to Intro to Javascript course

### ISSUE THREAD

**Issue by rkrupnick** [udacity/fend-issues#264]

**Comment by hbkwong** [comment]
Hi @rkrupnick, thanks for reporting. We'll get this updated ASAP.

Where exactly are you seeing this broken link?

**Comment by hbkwong** [comment]
Nevermind, found it! The original link actually already redirects to the correct course (https://www.udacity.com/course/intro-to-javascript--ud803), but I changed it just in case.
