### ISSUE TITLE
Setting Your Own 'this' possible quiz issue

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#271]
https://classroom.udacity.com/nanodegrees/nd001/parts/c02fda3b-67bf-48d6-a64f-c6960e2d4d79/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/7a95cd0f-752d-422e-b5a4-af8ddeaca0aa/concepts/f55148aa-4cb0-423a-8589-e85d99535919

Exploring JS- Objects, Tools and Testing
Lesson 9: Classes and Objects
4. Setting Your Own 'this'

 think there's an error for this quiz, unless I'm really missing something...

const andrew = { 
name: 'Andrew' 
};

function introduce(language) { 
console.log(`I'm ${this.name} and my favorite programming language is ${language}.`); 
}

Write an expression that uses the call() method to produce the message: 'I'm Andrew and my favorite programming language is JavaScript.

Answer: 
introduce.call(andrew, 'Javascript');

Won't pass me. Works in console.

**Comment by hbkwong** [comment]
Answered this one in Knowledge earlier! "JavaScript" is spelled incorrectly in the student's response (so the wrong string message is created).
