### ISSUE TITLE
Broken Course Links Android and iOS

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#273]
https://classroom.udacity.com/nanodegrees/nd001/parts/c02fda3b-67bf-48d6-a64f-c6960e2d4d79/modules/d91b4314-da9f-45ea-902e-0b1fb5a06c34/lessons/8085130355/concepts/84792620370923#

3. Exploring JS-Objects, Tools and Testing
6. Style
9. Mobile Screen Readers

The links taking you to the Android tutorial and iOS tutorial don't work.

**Comment by hbkwong** [comment]
Removed the links! With versioning and all, it'll be very tricky to maintain.
