### ISSUE TITLE
L23-C4: Typo, Missing parenthesis

### ISSUE THREAD

**Issue by adsingh14** [udacity/fend-issues#277]
There are total 3 parenthesis which tells about the missing parenthesis. 

![Missing Brace](https://user-images.githubusercontent.com/35252877/42467262-131012e2-83cf-11e8-93a5-a42f7dd3cac8.png)

**Comment by hbkwong** [comment]
Markdown didn't like the parenthesis in the URL. I fixed the link. THanks @adsingh14!
