### ISSUE TITLE
Broken Link- "destructuring"

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#281]
https://classroom.udacity.com/nanodegrees/nd001/parts/a76bb181-979a-4b36-b32f-01bced6e363e/modules/4116dc31-6d06-4774-b082-d60ca0980d2b/lessons/42383e89-ac6a-491a-b7d0-198851287bbe/concepts/59aad850-4429-42b8-a9e8-f4a7dded102f#

Lesson 8: Syntax
15... Rest Paramater 

"destructuring" link does not work

**Comment by hbkwong** [comment]
Fixed! Classroom links might be tied to versions, so I removed it entirely.
