### ISSUE TITLE
Prototypal Inheritance- typo

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#286]
Found a small innocent mistake in the nanodegree program. Thought i will share it so it can be resolved. In the 3rd curriculum "Exploring JS" - Lesson 9 - "Classes and Objects" - "5. Prototypal Inheritance" - First row, it is "as well as the means the manipulate that data" instead of "as well as the means TO manipulate that data"

https://classroom.udacity.com/nanodegrees/nd001/parts/c02fda3b-67bf-48d6-a64f-c6960e2d4d79/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/7a95cd0f-752d-422e-b5a4-af8ddeaca0aa/concepts/ab0184cb-2341-4ece-91f9-8c1a971769d0

**Comment by hbkwong** [comment]
Easy fix. Can't believe the typo's been there for that long!  Thanks Jess
