### ISSUE TITLE
Incorrect id in Pixel Art Maker GitHub repo

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#289]
The starter code in the GitHub repo https://github.com/udacity/project-pixel-art-maker-starter

has the id for the width input as `inputWeight` not `inputWidth`.  
***line 16***
```
        <input type="number" id="inputWeight" name="width" min="1" value="1">
````

I know most students will use  the Workspace to complete this exercise, but for students who are struggling with the project, the Workspace does not provide helpful feedback so I've been suggesting that they do the project in their code editor first.  It would help if the repo matched the code in the Workspace.

**Comment by hbkwong** [comment]
Definitely won't need the user's weight for this app (that was such an odd error). Fixed -- and thanks for your input as always Sarah!
