### ISSUE TITLE
Another Type of Loop (6-8) Quiz passes with incorrect code

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#3]
The instructions say "Print the test array to the console." but the quiz will pass if the updated values are printed to the console individually -- not as part of an array.

Link to quiz: https://classroom.udacity.com/nanodegrees/nd001/parts/9d3a4440-1e65-4fc5-9ac1-b40e401ad069/modules/cd56eea9-99b5-40c8-8725-a66a651e1ff0/lessons/378e7ff7-f7e5-4487-b5c4-fdf9b5c351d9/concepts/4c880baa-e51b-4b8e-bea0-50c5849688dd#

Code that passes but shouldn't:

test.forEach(function(num){
   if(num % 3 === 0) {
       num += 100;
   }
   console.log(num);
});

**Comment by richardkalehoff** [comment]
I've updated this quiz. It now correctly rejects this (and similar) solutions!
