### ISSUE TITLE
Feedback Extension does not work in Firefox

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#30]
Reported by a student.  I tested it and confirmed that it does not work.

**Comment by sarah-maris** [comment]
![capture](https://user-images.githubusercontent.com/6298143/29000158-743de632-7a31-11e7-8ad2-920f537a6e6d.PNG)

**Comment by sarah-maris** [comment]
![feedbackx](https://user-images.githubusercontent.com/6298143/29000160-87836dac-7a31-11e7-8dd9-bbe7d953c5f0.PNG)

**Comment by sarah-maris** [comment]
This is the message that  appears.  The only way we could get the Feedback extension to work was to load the test code into a local file

**Comment by richardkalehoff** [comment]
We are working on a replacement to the Udacity Feedback Extension. Once it is completed we will update FEND by swapping out quizzes that depend on the extension with the new tool.
