### ISSUE TITLE
Part of Slack Card quiz does not work in Firefox

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#31]
The border-radius test will not pass in Firefox -- same code does work in Chrome

**Comment by sarah-maris** [comment]
![image](https://user-images.githubusercontent.com/6298143/29007871-60b2cafc-7ada-11e7-98f2-0fb537374b0c.png)

**Comment by richardkalehoff** [comment]
We are working on a replacement to the Udacity Feedback Extension. Once it is completed we will update FEND by swapping out quizzes that depend on the extension with the new tool.
