### ISSUE TITLE
Instruction correction on Quiz: Build a Triangle (5-3)

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/fend-issues#32]
JavaScript Foundations => Lesson  5. Functions => 16. Quiz: Build a Triangle (5-3)

For this quiz the instruction says:

Create a function called buildTriangle() that will accept an input and will build a triangle.

and the example shows buildTriangle(10); building the triangle.

The quiz accepts the code only if the buildTriangle returns the triangle as a srting value and console.log(buildTriangle(10)); prints the triangle.

**Comment by forbiddenvoid** [comment]
Thanks for this feedback! I've made some updates to the content to make this clearer.

**Comment by ravikumarseth** [comment]
The instructions in this quiz might need further modification as the example shows `buildTriangle(10);` making the triangle which is still confusing.

The code

```
function makeLine(length) {
    var line = "";
    for (var j = 1; j <= length; j++) {
        line += "* ";
    }
    return line + "\n";
}

function buildTriangle(length) { 
    var triangle = ""; 
    for (var i = 1; i<= length; i++) { 
        triangle += makeLine(i);
    } 
    console.log(triangle);
}

buildTriangle(10);
```

will build the triangle but will still fail quiz tests.

Modifying the test or changing the example from `buildTriangle(10);`  to `console.log(buildTriangle(10)); ` is still somewhat necessary.
