### ISSUE TITLE
All test cases not passing on Firefox Feedback Extension

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/fend-issues#33]
Web Foundations => 8. CSS Syntax Problem Set => 8. Udacity Site Header

Font-weight test case not passing on despite the right answer. All other test cases are passing.

**Comment by richardkalehoff** [comment]
We are working on a replacement to the Udacity Feedback Extension. Once it is completed we will update FEND by swapping out quizzes that depend on the extension with the new tool.
