### ISSUE TITLE
Constant is being modified in the video lecture

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/fend-issues#34]
Video Link: https://classroom.udacity.com/nanodegrees/nd001/parts/516663e9-a691-4993-8872-bee0a05033a5/modules/4116dc31-6d06-4774-b082-d60ca0980d2b/lessons/42383e89-ac6a-491a-b7d0-198851287bbe/concepts/c48f069c-9de8-4dc4-ab3a-44036400a02d

2. JavaScript Foundations => Lesson 8: Syntax => Video 10: Iteration

Constant is being modified in the for loop 

for(const i = 0;  i< 10; i++){...}

**Comment by richardkalehoff** [comment]
I have updated the source content and have passed this along to the video team. When they create an updated video, I'll replace it in the classroom. Thanks!

**Comment by richardkalehoff** [comment]
I received the updated video back and have replaced the incorrect one with the new one! Thanks for submitting this ticket and making the course better :raised_hands:
