### ISSUE TITLE
Intermediate JavaScript Lesson 2 Quiz 2

### ISSUE THREAD

**Issue by developingharry** [udacity/fend-issues#35]
I couldn't get a correct answer, even if I copied the correct answer from the solution video.  I think I understand the answer given, but the validator thingy doesn't seem to like any of my ideas.  Also, the quiz afterwards, Quiz 3, on success, congratulates me for selecting the nav element, which wasn't the remit.

**Comment by veronikabenkeser** [comment]
Please contact a mentor for assistance with the content of the course. For Quiz 3, could you please post your code and a screenshot of the problem?

**Comment by hbkwong** [comment]
@developingharry, totally agree with Veronika on this one. Just wanted to check in: are you still running into issues with this one though? Let's get any roadblocks out of your way!

**Comment by hbkwong** [comment]
Closing this for now. @developingharry, if the quiz is still throwing some errors, feel free to re-open (or shoot me a Slack directly!)
