### ISSUE TITLE
Incorrect rendering of HTML in "A Full Request" lesson makes content difficult to follow

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#36]
This lesson did not make sense.  First, the text is awkwardly displayed.   Some text that should not be code is formatted as code.  This is what it looks like:

![bad render](https://user-images.githubusercontent.com/6298143/30038509-5ef8bc06-9193-11e7-9f19-fbff21e7df6a.PNG)

**_But I think it was intended to look like this (much easier to read)_**

Here's the full code that we've built up that creates the XHR object, tells it what info to request, sets up handlers for a success or error, and then actually sends the request:
```
 asyncRequestObject = new XMLHttpRequest();
 asyncRequestObject.open('GET', 'https://unsplash.com');
 asyncRequestObject.onload = handleSuccess;
 asyncRequestObject.onerror = handleError;
 asyncRequestObject.send();
```
**APIs and JSON**
 Getting the HTML of a website is ok, but it's probably not very useful. The data it returns is in a format that is extremely difficult to parse and consume. It would be a lot easier if we could get just the data we want in an easily formatted data structure. If you're thinking that JSON would be a good idea, then you're right and I'll give you a piece of my cake!

Instead of requesting the base URL for Unsplash, let's create an app that pulls an image from Unsplash's API and relevant articles from the New York Times.

When making a request from an API that returns JSON, all we need to do is convert that JSON response into a JavaScript object. We can do that with `JSON.parse();`. Let's tweak the onload function to handle a JSON response:

```
function handleSuccess () {
const data = JSON.parse( this.responseText ); // convert data from JSON to a JavaScript object
console.log( data );
}

asyncRequestObject.onload = handleSuccess;
```

Here is the lesson link in FEND::  
https://classroom.udacity.com/nanodegrees/nd001/parts/91561162-9864-4caf-b2aa-e6504385e4e2/modules/3cc28649-e29e-4095-8dc9-d7943de84d87/lessons/8cb1042e-3260-469c-9f78-8e2f092a4725/concepts/b097333c-2fc3-43b1-8141-5812fcd4a4a6

Same lesson in REACTND:
https://classroom.udacity.com/nanodegrees/nd019/parts/c5795c43-ebd1-4da9-8af9-db1c95ccf9e4/modules/b19830db-a890-435a-9a2c-3f5394b0df08/lessons/46eaae46-af74-4264-9393-15fe8c3357ca/concepts/b097333c-2fc3-43b1-8141-5812fcd4a4a6

**Comment by richardkalehoff** [comment]
This has been fixed, thanks! :+1:
