### ISSUE TITLE
Typo in code in Setting a Request Header lesson

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#37]
Code is: `unsplasRequest.send();`    -- missing an `h` in `unsplash`  -- should be:
`unsplashRequest.send();`

FEND lesson link:  https://classroom.udacity.com/nanodegrees/nd001/parts/91561162-9864-4caf-b2aa-e6504385e4e2/modules/3cc28649-e29e-4095-8dc9-d7943de84d87/lessons/8cb1042e-3260-469c-9f78-8e2f092a4725/concepts/9795d421-8e6c-4ab4-85ad-5b786aa36238

REACTND lesson link:
https://classroom.udacity.com/nanodegrees/nd019/parts/c5795c43-ebd1-4da9-8af9-db1c95ccf9e4/modules/b19830db-a890-435a-9a2c-3f5394b0df08/lessons/46eaae46-af74-4264-9393-15fe8c3357ca/concepts/9795d421-8e6c-4ab4-85ad-5b786aa36238

**Comment by sarah-maris** [comment]
FEND lesson link:  https://classroom.udacity.com/nanodegrees/nd001/parts/91561162-9864-4caf-b2aa-e6504385e4e2/modules/3cc28649-e29e-4095-8dc9-d7943de84d87/lessons/8cb1042e-3260-469c-9f78-8e2f092a4725/concepts/9795d421-8e6c-4ab4-85ad-5b786aa36238

REACTND lesson link:
https://classroom.udacity.com/nanodegrees/nd019/parts/c5795c43-ebd1-4da9-8af9-db1c95ccf9e4/modules/b19830db-a890-435a-9a2c-3f5394b0df08/lessons/46eaae46-af74-4264-9393-15fe8c3357ca/concepts/9795d421-8e6c-4ab4-85ad-5b786aa36238

**Comment by veronikabenkeser** [comment]
Bug does not currently appear in FEND. Fixed the bug in REACTND.
