### ISSUE TITLE
Incorrect sequence in AJAX with XHR course

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#38]
The sequence of the AJAX with XHR course is different in the FEND and REACTND programs:

**FEND sequence**
![fend sequence](https://user-images.githubusercontent.com/6298143/30038987-ee046396-9198-11e7-84f5-a301f947c0a0.PNG)

**REACTND sequence**
![react sequence](https://user-images.githubusercontent.com/6298143/30038988-ee0550f8-9198-11e7-8507-f085bd612dcb.PNG)

The REACTND sequence makes more sense since the `open()` and `send()` methods used in the Initial Walkthrough lesson are covered ***after*** that lesson in the FEND sequence:
![image](https://user-images.githubusercontent.com/6298143/30039019-44ffcbb8-9199-11e7-9b74-381b954365a3.png)

**Comment by richardkalehoff** [comment]
The ReactND sequence is the correct one. Not sure how the Project Initial Walkthrough page got bumped up in FEND. In any case, I've corrected it! Thanks, Sarah :+1:
