### ISSUE TITLE
Incorrect  HTML rendering of text in XHR's .send() method lesson

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#39]
This is what it looks like:
![image](https://user-images.githubusercontent.com/6298143/30039042-a2b4ab2a-9199-11e7-9a41-2f13e64832ca.png)

I'm guessing it should be:

**Handling Errors**
You might've picked up that `onload` is called when the response is successful. If something happens with the request and it can't be fulfilled, then we need to use the `onerror` property:
```
function handleError () {
// in the function, the `this` value is the XHR object
  console.log( 'An error occurred' );
}

asyncRequestObject.onerror = handleError;
```

As with `onload`, if `onerror` isn't set and an error occurs, that error will just fail silently and your code (and your user!) won't have any idea what's wrong or any way to recover."

Link to FEND lesson:
https://classroom.udacity.com/nanodegrees/nd001/parts/91561162-9864-4caf-b2aa-e6504385e4e2/modules/3cc28649-e29e-4095-8dc9-d7943de84d87/lessons/8cb1042e-3260-469c-9f78-8e2f092a4725/concepts/0cd27aed-f95a-4148-ab61-c910b90d32a0

Link to REACTND lesson:
https://classroom.udacity.com/nanodegrees/nd019/parts/c5795c43-ebd1-4da9-8af9-db1c95ccf9e4/modules/b19830db-a890-435a-9a2c-3f5394b0df08/lessons/46eaae46-af74-4264-9393-15fe8c3357ca/concepts/0cd27aed-f95a-4148-ab61-c910b90d32a0

**Comment by richardkalehoff** [comment]
This has been updated, thanks! :+1:
