### ISSUE TITLE
Udacity Site Header Quiz - 200px image width

### ISSUE THREAD

**Issue by kboling** [udacity/fend-issues#4]

**Comment by kboling** [comment]
I have completed 4/5 objectives. I have changed the logo width and the feedback tool is not seeing. I also have seen that the test widget for that objective is worded correctly but its not being accepted. The edited code is below: 

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Udacity Site Header</title>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
  <meta name="udacity-grader" content="tests.json">
  <style>
    * {
      box-sizing: border-box;
    }
    body {
      font-family: 'Open Sans', sans-serif;
      background-color: #ddd; <------------------------------------------------True
      margin: 0;
      padding: 0;
    }
    header {
      font-weight: 400; <-----------------------------------------------------------True
      -webkit-font-smoothing: antialiased;
      color: #697681; <-------------------------------------------------------------- True
      background: white;
      height: 85px;
      padding: 15px;
    }
    section {
      padding: 16px;
    }
    .flex-container {
      display: flex;
    }
    .space-between {
      justify-content: space-between;
    }
    .vertical-centerer {
      height: 100%;
      flex-direction: column;
      justify-content: center;
    }
    .header-content {
      width: 960px;
      margin-left: auto;
      margin-right: auto;
    }
    .logo {
      width: 200px; <---------------------------------------------------------------Error!
      display: inline-block;
      margin: 10px 0px;
    }
    .menu {
      list-style: none;
      list-style-type: none;
    }
    .menu > li {
      display: inline;
      margin-left: 37.5px;
    }
  </style>
</head>
<body>
  <header>
    <div class="vertical-centerer flex-container">
      <div class="flex-container space-between header-content">
        <div>
          <span>
            <img class="logo" src="http://udacity.github.io/fend/lessons/L3/problem-set/08-udacity-site-header/Udacity_Logo_SVG_200x35.svg" alt="Udacity Logo">
          </span>
        </div>
        <div>
          <ul class="menu">
            <li>Nanodegree</li>
            <li>Catalog</li>
            <li>Classroom</li>
          </ul>
        </div>
      </div>
    </div>
  </header>
  <section>
    <p>Ewww. The header looks weird.</p>

    <p>
      You need to use Developer Tools to edit this website and pass this quiz. Make sure you read the criteria carefully because they contain the exact CSS properties that you need to change!
    </p>
  </section>
</body>
</html>


![Screen Shot 2017-06-30 at 1.55.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5957eb6e0fdf33001aca93fd/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256457f36b7191a379f1172e4f5d575ecc3c4a4356bcbbd671f3e57862804e0ee4d46f0c21903410febc871fec01ba228e1e81b7efdb49d2f42f67b6d5db1063474f4dcbed5727a29f41c95cff43e84e51a51a326ae3742431.png)

**Comment by richardkalehoff** [comment]
For reference:
* [Project](http://udacity.github.io/fend/lessons/L3/problem-set/08-udacity-site-header/)
* [Repo](https://github.com/udacity/fend/tree/gh-pages/lessons/L3/problem-set/08-udacity-site-header)

**Comment by richardkalehoff** [comment]
Looks like you've done exactly what you're supposed to be doing on this quiz! I just tested it myself with your code, and it worked perfectly...so I'm not sure why it wasn't working for you. Your code is correct, though, so keep up the good work! :+1:
