### ISSUE TITLE
Incorrect HTML formatting in "Display Content & Handling Errors" lesson

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#40]
This text is difficult to read:

Display Content & Handling Errors
![image](https://user-images.githubusercontent.com/6298143/30065519-24a19560-9223-11e7-922a-5bd622922980.png)

It looks like it should be an unordered list:

**Handling Errors**
Our app is now done with getting the image from Unsplash!...almost. We're requesting the image and adding it to the page, but this is only one possible outcome. Granted, it's the most likely way that the app will end up, but we're not handling any errors. What errors could possible happen you ask? A couple I can think of are:

- issues with the network 
- issues with the fetch request 
- Unsplash not having an image for the searched term

**Comment by richardkalehoff** [comment]
Seems like by the time I got to this, someone else had already fixed it, because it's showing as a bulleted list now! Thanks, Sarah! :raised_hands:
