### ISSUE TITLE
Pixel Art Maker repo doesn't follow Udacity's Style Guide

### ISSUE THREAD

**Issue by csiszi** [udacity/fend-issues#41]
The [CSS Style Guide](http://udacity.github.io/frontend-nanodegree-styleguide/css.html#selector-declaration-separation) says:

> Always start a new line for each selector and declaration.

I've just created a [PR](https://github.com/udacity/project-pixel-art-maker-starter/pull/5).

**Comment by csiszi** [comment]
@richardkalehoff Just for future reference, should we make PRs?

**Comment by richardkalehoff** [comment]
Yes, PRs are definitely appreciated! :+1:

**Comment by richardkalehoff** [comment]
I've merged in your PR. Thanks!
