### ISSUE TITLE
Ajax with fetch course part 7

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#43]
https://classroom.udacity.com/nanodegrees/nd001/parts/91561162-9864-4caf-b2aa-e6504385e4e2/modules/3cc28649-e29e-4095-8dc9-d7943de84d87/lessons/7cd5017a-cdce-463f-ba13-e53603fa83eb/concepts/18a6772b-7c45-4f23-8479-dd294633245a

Location: Lesson 5: Ajax with Fetch 7. Display Content & Handling Errors 

Info from student: The code for adding .catch method to fetch has a bug here the. catch method should be placed right after the fetch method but in the code its written after addImage function please rectify this bug.

Zendesk Ticket #573448

**Comment by richardkalehoff** [comment]
I've moved `.catch()` to the correct location :+1:

**Comment by JessicaBettencourt** [comment]
Thank you!
