### ISSUE TITLE
Broken Link menu.html

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#44]
https://classroom.udacity.com/nanodegrees/nd004-connect/parts/52f50785-064e-4221-9227-e5c076a840d0/modules/348776022975460/lessons/3593308717/concepts/36245586210923

menu.html link at bottom left needs updating

**Comment by richardkalehoff** [comment]
The link seems to be working correctly, so closing this ticket. Feel free to reopen if there's a problem.
