### ISSUE TITLE
2 Broken Links Recalculate Styles

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#45]
https://classroom.udacity.com/nanodegrees/nd001/parts/e87c34bf-a9c0-415f-b007-c2c2d7eead73/modules/273584856175461/lessons/4147498575/concepts/41727285740923

Broken Links:
-"Here's a live version of the site for your refactoring!"
-"Here's a downloadable version of the site for your refactoring!"

**Comment by richardkalehoff** [comment]
This might be a tough one. The links are to a Dropbox account that no longer exists. I'll see if I can track it down from Cameron Pittman and/or Paul Lewis.

**Comment by richardkalehoff** [comment]
Was finally able to track down the code for this course. The link has been fixed and now points to the project on GitHub.
