### ISSUE TITLE
Broken Link Painting and Compositing

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#46]
https://classroom.udacity.com/nanodegrees/nd001/parts/e87c34bf-a9c0-415f-b007-c2c2d7eead73/modules/273584856175461/lessons/4129068601/concepts/41339989350923

Broken Link: "Here's the site for your analysis"

Version 1

**Comment by richardkalehoff** [comment]
I've updated the link to the correct page :+1:
