### ISSUE TITLE
Small problem in CC

### ISSUE THREAD

**Issue by csiszi** [udacity/fend-issues#47]
React ND / React & Redux / Why Redux? / Introduction video:
https://photos.app.goo.gl/wbapMi95phavt5jg2

**Comment by hbkwong** [comment]
Perfect, thanks for catching this one @csiszi. I've pushed an update to our subtitles repo and it should be merged shortly. Moving forward, feel free to check out the ReactND Waffle board for any future issues/feedback: https://waffle.io/udacity/reactnd-issues

Enjoy the rest of your week!
