### ISSUE TITLE
Broken "Sets" Link

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#48]
https://classroom.udacity.com/nanodegrees/nd001/parts/516663e9-a691-4993-8872-bee0a05033a5/modules/4116dc31-6d06-4774-b082-d60ca0980d2b/lessons/42383e89-ac6a-491a-b7d0-198851287bbe/concepts/398d36e6-3393-4c50-b870-44a4dffb0ac4

FEND Version 6.0

The text says: 
"If you look at the output from the examples, notice that both the array and set have been expanded into their individual elements. So how is this useful?
NOTE: Sets are a new built-in object in ES6, we’ll cover Sets in more detail later in lesson 3."

"There is a link in "we'll cover Sets". When I click it to see the Sets content in lesson 3, I do not have access."

Zendesk Ticket #579267

**Comment by richardkalehoff** [comment]
Since this content is used by multiple Nanodegree programs, I've updated the text to remove the link and changed the text to say that it'll be coming in a future lesson.
