### ISSUE TITLE
No link to starter code in Ajax with XHR course

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#49]
Lesson:  Project Initial Walkthrough
https://classroom.udacity.com/nanodegrees/nd001/parts/91561162-9864-4caf-b2aa-e6504385e4e2/modules/3cc28649-e29e-4095-8dc9-d7943de84d87/lessons/8cb1042e-3260-469c-9f78-8e2f092a4725/concepts/685ff9da-fbaa-400c-94ae-72ab42743137

The video refers to a project -- shows the project -- but does not provide a link to the code. 

I believe this is the correct code: https://github.com/udacity/course-ajax/tree/master/lesson-1-async-w-xhr

**Comment by sarah-maris** [comment]
Actually a better link would be this one :  https://github.com/udacity/course-ajax because it includes the CSS

**Comment by richardkalehoff** [comment]
I've added a link to the course to the starter project :+1:
