### ISSUE TITLE
Twilio video shows outdated material

### ISSUE THREAD

**Issue by twhetzel** [udacity/fend-issues#5]
The Twilio client (https://www.twilio.com/docs/libraries/python) is updated and the Udacity video no longer shows the correct information.

**Comment by twhetzel** [comment]
Lesson 7: Use classes:Send Text at https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/356120945175460/lessons/991551862/concepts/10134987320923

**Comment by richardkalehoff** [comment]
Thanks for the link, twhetzel! I've updated the page :+1:
