### ISSUE TITLE
Missing Link to Repo: Ajax Course

### ISSUE THREAD

**Issue by orhnyslz** [udacity/fend-issues#51]
The link to the repo is missing for the Ajax course. The "Project Initial Walkthrough" section would be perfect for it. Here is the link to the repo: https://github.com/udacity/course-ajax

**Comment by richardkalehoff** [comment]
Hey, Orhan :wave: I actually just updated this based on another ticket, so the content should be there now! Thanks for submitting! :raised_hands:

**Comment by orhnyslz** [comment]
That was quick - thanks Richard! :)
