### ISSUE TITLE
Neighborhood Map Project Details- Broken Link

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#55]
https://classroom.udacity.com/nanodegrees/nd004/parts/135b6edc-f1cd-4cd9-b831-1908ede75737/modules/4fd8d440-9428-4de7-93c0-4dca17a36700/lessons/2711658591239847/concepts/26906985370923

Broken link: "Javascript Design Patterns"

Should be https://www.udacity.com/course/javascript-design-patterns--ud989

Ticket #598753

**Comment by richardkalehoff** [comment]
Fixed! :+1:
