### ISSUE TITLE
Speedster autocomplete quiz input form fields disabled

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#56]
Link to lesson: https://classroom.udacity.com/nanodegrees/nd001/parts/91561162-9864-4caf-b2aa-e6504385e4e2/modules/4fd8d440-9428-4de7-93c0-4dca17a36700/lessons/8306134879/concepts/83070349060923

link to quiz page: https://google-developers.appspot.com/maps/documentation/javascript/examples/full/places-autocomplete-addressform

The quiz instructs the students to fill in the form by typing. 

![instructions](https://user-images.githubusercontent.com/6298143/31793807-49201932-b4ee-11e7-86b0-665cdc7209ff.PNG)

 But they can't because all of the input boxes are set to disabled

![disabled fields in quiz](https://user-images.githubusercontent.com/6298143/31793806-4911e2ea-b4ee-11e7-80df-37f5e3fedb3a.PNG)

**Comment by asparr** [comment]
Hi Sarah, it looks like the field is actually above the box and the address is entered there in full. 
![Screenshot 2017-10-26 14.43.05.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588be5508698331a0016c5bd/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36417773e7b52e37a24cbb77bf1122e43434d0eee1e020a17b8eb8339a3bf3972d9095de4d03f5b71c66e11acba874ebb00e9718e5d99a4fedb1294b7607caddecd5d340c071983fe5835a9994ecc5af648e14e50b65e.png)

**Comment by asparr** [comment]
We've decided to deprecate this quiz, as the app referred to is no longer supported by the instructor and does not match the instructions.
