### ISSUE TITLE
Build a Portfolio Site- Mockup

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#57]
https://classroom.udacity.com/nanodegrees/nd001/parts/516663e9-a691-4993-8872-bee0a05033a5/modules/273669854375463/lessons/2736698543239847/concepts/26558985860923#

design-mockup-portfolio.pdf at the bottom of the page takes student to 403

Ticket #602755

**Comment by asparr** [comment]
@JessicaBettencourt I think this may have been resolved via another JIRA ticket that duplicated this issue, or perhaps the student's connection is blocking them from some links due to security protocols. Closing for now.
