### ISSUE TITLE
Super and Extends Functions

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#58]
https://classroom.udacity.com/nanodegrees/nd001/parts/9e34624d-cdc8-4cd7-9d7e-78943413e645/modules/2fc0e696-4879-47f6-afeb-48730cd8fb1e/lessons/3925704a-be38-4b70-8c8b-a4a812b6a309/concepts/6b91f1d9-e0e0-43b7-815f-1a9a47b78a1d 

"The explanation here adds the following code:

class Maple extends Tree { 
constructor(syrupQty = 15, size, barkColor, leaves) { 
super(size, barkColor, leaves); 
this.syrupQty = syrupQty; 
}

But as I can see in the whole page, there is no mention for parameter “barkColor” in the superClass. Which is meaningless to be in the super() function. It just causes confusion"

Ticket #601193

**Comment by richardkalehoff** [comment]
The `barkColor` argument was left over from a previous version of this code. I've removed it.
