### ISSUE TITLE
Instructions for Quiz: Laugh it Off 2 (5-2) not comprehensive

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#6]
A student tried to use `.repeat()` instead of a loop for this quiz -- but the code will not pass, even though it produces the correct output.

Link to Quiz: Laugh it Off 2 (5-2):  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

See post here.:
https://discussions.udacity.com/t/quiz-laugh-it-off-2-5-2/216280/60?u=sarah_m

**Comment by richardkalehoff** [comment]
There were issues with this quiz's grading code that I have corrected. I tested the student's code, and it works correctly now.
