### ISSUE TITLE
Misleading instructions in Quiz: One Awesome Message (2-12)

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#60]
Link to quiz: 
https://classroom.udacity.com/nanodegrees/nd001/parts/516663e9-a691-4993-8872-bee0a05033a5/modules/cd56eea9-99b5-40c8-8725-a66a651e1ff0/lessons/74007e2e-2a0a-4de3-a8a6-5c2ec4275773/concepts/3c43abc9-d9c6-4e55-bceb-08b119fff788#

The instructions tell the student to include `"to"` in the `hobby` string:
```
/*
 * Notes:
 * - Using the above as an example, firstName would have been assigned to
 *   "Julia", interest to "cats", and hobby to "to play video games".
 */
```
but to pass the quiz the student must have `"to"` in the connector string.  So if the student follows the instructions in the note they can only pass if their message reads:
```
Hi, my name is Julia. I love cats. In my spare time, I like to to play video games.
```
This is very frustrating for the students...

See more here: https://discussions.udacity.com/t/bug-in-24-quiz-one-awesome-message-2-12-lesson-11/426104/8?u=sarah_m

**Comment by aayusharora** [comment]
Thanks @sarah-maris, I have seen a lot of discussion on the forum regarding this which is confusing many students in gchallenge, hope it is fixed soon.

**Comment by veronikabenkeser** [comment]
Thank you for bringing this up! I have updated the quiz. To see the changes in the Classroom, the student needs to press the "Reset Quiz" button in the Classroom. It works this way so that we can make changes to quizzes without altering the progress of any students who have already started the quiz.
