### ISSUE TITLE
Color code transcript typo

### ISSUE THREAD

**Issue by SittingFox** [udacity/fend-issues#64]
A student pointed out that a video transcript says `0000lf` when it should say `0000ff`.

This happens in the quiz answer here, at time 0:58.
https://classroom.udacity.com/nanodegrees/nd001/parts/d4012321-b4fa-4628-9121-2baf37385560/modules/a605c5ff-eaf7-4882-9c6f-9e65a33c8b59/lessons/7473321627/concepts/74276264330923

Link to thread where the issue is brought up (Google Scholarship Challenge): https://discussions.udacity.com/t/transcript-mistake/435906

**Comment by hbkwong** [comment]
Hmm, I just checked the subtitles repo and `jTDav9Q9TaA.srt`does seem to include the correct value (`0000ff`). Let me dig a bit further one this one.

**Comment by hbkwong** [comment]
Looks like the video is still stuck on `0000lf`. I've reached out to the localization team see what's going on.

**Comment by hbkwong** [comment]
Should be good to go: https://github.com/udacity/subtitles/pull/2539
