### ISSUE TITLE
Typo- HTML Structure Part 2

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#66]
https://classroom.udacity.com/courses/ud304-emea/lessons/6987421963/concepts/4a788a8e-2d58-4ba3-9469-c1728c410dea

In this paragraph... "leave" is written 2x.

Omitting some of this information doesn't necessarily mean that the page won't be displayed. In fact, your browser will assume certain parts of the template exist even if you accidentally leave leave them out. Take this line of HTML for example:

**Comment by richardkalehoff** [comment]
I've removed the duplicate "leave".
