### ISSUE TITLE
Constructing Links Feedback

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#67]
https://classroom.udacity.com/courses/ud304-emea/lessons/7222405183/concepts/73229895910923

Lesson 3: HTML Syntax Problem Set

8. Constructing Links

A student suggested to add "Quiz" on the menu bar, to clarify that there will be a quiz in that section.

**Comment by veronikabenkeser** [comment]
Added the word "Quiz" to the title to make it clear that the section contains a quiz.
