### ISSUE TITLE
Possible Quiz Bug- Converting Temperatures

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#68]
https://classroom.udacity.com/courses/ud304-emea/lessons/74007e2e-2a0a-4de3-a8a6-5c2ec4275773/concepts/5f0a00eb-e0c7-4b3f-a24d-400cad12176e

Message from student:
I just encountered what I think might be a bug in the quiz, here is what I wrote:

/* 
* Programming Quiz: Converting Tempatures (2-2) 
* 
* Use the Celsius-to-Fahrenheit formula to set the fahrenheit varible: 
* 
* F = C x 1.8 + 32 
* 
* Log the fahrenheit variable to the console. 
* 
*/

var celsius = 12; 
var fahrenheit = celsius*1.8+32;

console.log(celsius+" degrees Celsius is equal to "+fahrenheit + " degrees Fahrenheit");

I enclosed the file of the feeback which basically says: 
What went well: your farheneit value should be 53.6 
What went wrong: your farheneit value is not correct.

As the quiz is not using a code, I cannot validate it which is a bit annoying.

Ticket #618728

**Comment by veronikabenkeser** [comment]
Verified that the quiz is working correctly. The student was printing the string "12 degrees Celsius is equal to 53.6  degrees Fahrenheit" instead of a single value.

**Comment by JessicaBettencourt** [comment]
Thank you!
