### ISSUE TITLE
Quiz Another Type of Loop (6-8)

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#69]
https://classroom.udacity.com/courses/ud304-emea/lessons/378e7ff7-f7e5-4487-b5c4-fdf9b5c351d9/concepts/4c880baa-e51b-4b8e-bea0-50c5849688dd#

Student reported empty frame at the top of the page. 

Ticket #617483
&
Ticket #620634

**Comment by veronikabenkeser** [comment]
The empty frame no longer appears. Closing this ticket.
