### ISSUE TITLE
Error in the Mentor Window 

### ISSUE THREAD

**Issue by IvanBila** [udacity/fend-issues#7]
I had this error in the mentor chat box. I have attached bellow the Console results when i had the error 
![error udacity](https://user-images.githubusercontent.com/13482373/27810002-8ca99658-6055-11e7-8404-e9131e5dd9a4.PNG)

![console](https://user-images.githubusercontent.com/13482373/27810004-8fd1d76e-6055-11e7-939b-abf37d2c7d1f.PNG)

**Comment by richardkalehoff** [comment]
Thanks for this feedback! I've sent this over to our Mentorship team. If they need further information, the Mentorship team will reach out to you.Since this isn't an issue with the Frontend Nanodegree, I'm closing this ticket for now.
