### ISSUE TITLE
Fend_Neighbourhood_map_issue

### ISSUE THREAD

**Issue by Sazameth** [udacity/fend-issues#71]
My flickr getflickr images is pulling one image correctly but I can see the others, kindly help. I have updated my flickr url, but still I get 1 photo, I have two exact photos in my flickr which correspond to my array name in script.js https://github.com/Sazameth/sazameth.github.io-MyNeigbourhoodPOI-Map.git

GitHub

Sazameth/sazameth.github.io-MyNeigbourhoodPOI-Map

sazameth.github.io-MyNeigbourhoodPOI-Map - Neighbourhood Map, POI

**Comment by richardkalehoff** [comment]
Hi Sazameth :wave: To get support with a project, please contact your mentor. I'll close this ticket since this isn't an issue with the program itself.

**Comment by Sazameth** [comment]
Thanks Richard
    On Friday, January 5, 2018, 12:54:50 AM GMT+3, Richard Kalehoff <notifications@github.com> wrote:  
 
 
Hi Sazameth 👋 To get support with a project, please contact your mentor. I'll close this ticket since this isn't an issue with the program itself.
