### ISSUE TITLE
Link to a Stylesheet- Path Link

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#73]
https://classroom.udacity.com/courses/ud304-emea/lessons/7323812069/concepts/74223546650923

The link "paths" (halfway down the page) scholarship students don't have access to. 

Ticket #620599

**Comment by hbkwong** [comment]
@JessicaBettencourt  This is an "old-style" quiz. The link itself can't be changed easily, but I've added some verbiage on this page to point students to the exact lesson should they have difficulty viewing the link.
