### ISSUE TITLE
Udacity Site Header quiz - now works in Canary but not in Chrome

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#75]
The opposite issue was reported earlier and apparently fixed.  But now the quiz appears to only work in Canary:

Link to quiz:  https://classroom.udacity.com/nanodegrees/nd001/parts/d4012321-b4fa-4628-9121-2baf37385560/modules/a605c5ff-eaf7-4882-9c6f-9e65a33c8b59/lessons/7323812069/concepts/75570469630923#

Quiz in Chrome (student image but I had same result)
![image](https://user-images.githubusercontent.com/6298143/32801506-461512da-c94b-11e7-8784-7e3a17752061.png)

Quiz in Canary:

![image](https://user-images.githubusercontent.com/6298143/32801575-7ebf8c6e-c94b-11e7-8edb-34f619d5a2a8.png)

**Comment by forbiddenvoid** [comment]
I've updated this test to accept both 400 and normal as values for the font-weight. Chrome is definitely changing some under-the-hood things about how they evaluate this in the browser, but this change should resolve the issue.
