### ISSUE TITLE
Inconsistent Grading in Factorial Quiz

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#77]
Link to Quiz: Factorials! (4-7):  https://classroom.udacity.com/nanodegrees/nd001/parts/516663e9-a691-4993-8872-bee0a05033a5/modules/cd56eea9-99b5-40c8-8725-a66a651e1ff0/lessons/1234cec0-179b-40b6-9435-f10263c7de33/concepts/371cff31-42a7-4e5e-93e2-f0c3dd5cc7d0#

The quiz will not pass if `x` is before `solution` in the multiplication :
```
var solution = 1;
for (var x = 1; x <= 12; x++) {
  solution = x * solution;
}
```
But it does pass with the assignment operator:
```
var solution = 1;
for (var x = 1; x <= 12; x++) {
  solution *= x;
}
```
Or if `solution` comes before `x`.
```
var solution = 1;
for (var x = 1; x <= 12; x++) {
  solution = solution * x;
}
```
But these are all mathematically equivalent and give the same answer:  `solution` = 479001600

**Comment by forbiddenvoid** [comment]
Fixed!
