### ISSUE TITLE
Javascript Basics Course Link

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#78]
https://classroom.udacity.com/nanodegrees/nd001/parts/9e34624d-cdc8-4cd7-9d7e-78943413e645/modules/269645859775460/lessons/2593668697/concepts/34797687890923

JavaScript Basics Course gives 404 error message

Ticket #628186

**Comment by hbkwong** [comment]
@JessicaBettencourt  I've updated the course to ud803 (Intro to JavaScript), since that's the course we offer in FEND. The page should be good to go now!
