### ISSUE TITLE
Pixel Art Maker grammar error

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#79]
https://review.udacity.com/#!/rubrics/641/view

‘The student implements while and for loops to clear and create the grid dynamically’.

And it should be: 'The student implements while or for loop to clear and create the grid dynamically.’

Ticket #628759

**Comment by hbkwong** [comment]
@forbiddenvoid, is a `while` loop a  _requirement_ to clear the table?

**Comment by hbkwong** [comment]
@JessicaBettencourt Just checked with David. It's indeed "or" (instead of "and")!

**Comment by hbkwong** [comment]
Just to close the loop: the link was updated earlier this week (i.e.,  641 is deprecated)
