### ISSUE TITLE
Dialog not showing completely 

### ISSUE THREAD

**Issue by IvanBila** [udacity/fend-issues#8]
Dialogs are not showing completely meaning a part of it is cut of and i don't have an option to scroll down to see the rest of the dialog. 

![capture](https://user-images.githubusercontent.com/13482373/27810132-e3dab938-6056-11e7-8f6b-b9d2745371ce.PNG)

**Comment by richardkalehoff** [comment]
Thanks for submitting this ticket, IvanBila! Could you post a link to the Udacity classroom page where you're experiencing this issue?

**Comment by IvanBila** [comment]
Here's the link @richardkalehoff : [Udacity](https://classroom.udacity.com/nanodegrees/nd001/parts/b846fc63-9195-42a1-97a8-f98a99100f32/modules/273669854375461/lessons/3533879576/concepts/35691989700923)
in order to reproduce the error you have to get the answer wrong in the quiz

**Comment by richardkalehoff** [comment]
Ivan, it appears as though you're using Chrome on Windows. We've tried that quiz on Chrome/Windows, and we *are* able to scroll up and down in that "Try Again" popup window. 

Do you know which version of Chrome and which version of Windows you're using?
