### ISSUE TITLE
jQuery load instructions outdated

### ISSUE THREAD

**Issue by vincegiorno** [udacity/fend-issues#81]
In the video How Is jQuery Included in a Page, part 7 in Lesson 1 (The Basics: the DOM, $, and Selector) of Intermediate JavaScript, students are learning "how to load" jQ version 1.11.1. I was wondering why so many projects I see use this outdated version, which is especially troublesome since it does not support error handling for the JSONP requests many students make. It would be great to edit this, or at least include a note under the video telling students to use a current version.

**Comment by forbiddenvoid** [comment]
Hey Vince, which projects are you seeing this used in?

**Comment by forbiddenvoid** [comment]
I added a note to the concept, but all of the links point to current versions of jQuery.

**Comment by vincegiorno** [comment]
Neighborhood Map projects, David. I keep seeing students who make JSONP calls resorting to setTimeout() for their error handling, since ajax() JSONP calls fail silently in jQ 1.11.1. I guess they go back to the lessons to see how to load jQuery, see 1.11.1 there on the screen and just copy what they see instead of going to the jQuery site and downloading what is currently available.
