### ISSUE TITLE
Write your First Promises Quiz - no "downloadables" section

### ISSUE THREAD

**Issue by kellim** [udacity/fend-issues#82]
The quiz says "1. Download setTimeout-start.zip from the downloadables section." 

However, the file is under "supporting materials" and there is nothing called a "downloadables" section that I can find.

**Comment by kellim** [comment]
Link: https://classroom.udacity.com/nanodegrees/nd001/parts/91561162-9864-4caf-b2aa-e6504385e4e2/modules/550593026975460/lessons/5972243496/concepts/60922094860923

**Comment by veronikabenkeser** [comment]
Hi Kelli, thank you for bringing this up! Just fixed it.
