### ISSUE TITLE
Problem with Lesson 15, Quiz 17, Question 3

### ISSUE THREAD

**Issue by aviaryan** [udacity/fend-issues#83]
Some students are having the following doubt in that question. Just quoting one such instance, 

>  I think, there is a fault in the Lesson 15, Quiz 17, Question 3:
What method(s) could you use to remove the first element from this array:
I think, that the correct answer should be shift() and splice(). To pass through I had to add slice()! But according the definition: “the slice() method returns a shallow copy of a portion of an array into a new array object selected from begin to end (end not included). The original array will not be modified.” So, it does not remove the first element from the given array, it just creates a copy of it without the first element!

Link: https://discussions.udacity.com/t/problem-with-lesson-15-quiz-17-question-3/488461

Is it alright to have `slice()` as one of the correct answers there? I think that it does not *remove* the first element of an array, as is asked in the question.

**Comment by hbkwong** [comment]
Hey @aviaryan, good catch. I'm with you on this one; with the way that the prompt was written, `shift()` and `splice() ` would technically be the correct answers. `slice()` doesn't actually mutate the original array. I'll update the prompt and some of the (in)correct-answer messages accordingly. Thanks for the heads up on this discussion!

**Comment by hbkwong** [comment]
The update should be live in just a bit. If you run into further questions/feedback, feel free to reach out! Have a wonderful holiday season, Avi.

**Comment by aviaryan** [comment]
Thank you @hbkwong for the quick resolution. Best wishes to you too. 😁
