### ISSUE TITLE
Typo JavaScript Classes "like like"

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#84]
https://classroom.udacity.com/nanodegrees/nd001/parts/9e34624d-cdc8-4cd7-9d7e-78943413e645/modules/2fc0e696-4879-47f6-afeb-48730cd8fb1e/lessons/3925704a-be38-4b70-8c8b-a4a812b6a309/concepts/a9105c4c-2ffb-4865-b24e-de09f570eb37#

ES6 Classes
Here's what that same Plane class would like like if it were written using the new class syntax:

Should say "Plane class would look like".

**Comment by hbkwong** [comment]
@JessicaBettencourt  Fixed! Thanks for the link

**Comment by JessicaBettencourt** [comment]
Thanks!
