### ISSUE TITLE
Ud304 Map minor typo

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#85]
https://classroom.udacity.com/courses/ud304-emea/lessons/378e7ff7-f7e5-4487-b5c4-fdf9b5c351d9/concepts/097cea31-4721-4887-adef-80e4354dc310

It’s on Lesson 15: Arrays, Section 21:Map. 
A semicolon is missing from the end of the first line of code. 

var donuts = ["jelly donut", "chocolate donut", "glazed donut"]
var improvedDonuts = donuts.map(function(donut) {
  donut += " hole";
  donut = donut.toUpperCase();
  return donut;
});

**Comment by hbkwong** [comment]
Fixed! Thanks @JessicaBettencourt
