### ISSUE TITLE
Create Bad README

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#86]
https://classroom.udacity.com/nanodegrees/nd001/parts/0a11a6d9-a730-4f9b-ad79-035d1e46c3f3/modules/40e87aee-db8f-45da-bd9a-182aa0150569/lessons/5447928618/concepts/53903291850923

Unfinished content: says [TODO] Create bad README.

FEND Version 7.0

**Comment by hbkwong** [comment]
@JessicaBettencourt  We've hidden the entire quiz for now, since the file is missing. We'll check in with Walter once he's back!

**Comment by JessicaBettencourt** [comment]
Great, thank you!
