### ISSUE TITLE
Typo Select Page Element by UD

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#87]
https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/74c2a096-61db-4302-9d65-6b7fa9b8c329/concepts/b3643239-ecef-483d-8b9f-af0613781feb

In the first paragraph. It says "We'll we're going to start using it! ". It should be "Well we're going to start using it!".

**Comment by hbkwong** [comment]
Fixed! Thanks again @JessicaBettencourt
