### ISSUE TITLE
Lesson 8:4.Scope >> QUESTION 2 OF 4  What will the console display when myFunction() is called?

### ISSUE THREAD

**Issue by avastamin** [udacity/fend-issues#88]
let n = 2;

function myFunction() {
  let n = 8;
  console.log(n);
}

myFunction();
// ???

Output should be `8` but system accepts 2

**Comment by hbkwong** [comment]
Hey @avastamin, good catch. Not sure why this happened, because even the modal that pops up after the "correct" answer says `8` too (as it should be). It's since been fixed. Thanks for reporting this one!

By the way, how is the course so far?
