### ISSUE TITLE
Invalid CSS rule in Hometown App (Project Part 1 solution)

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#9]
Here is the link to the quiz:  https://classroom.udacity.com/nanodegrees/nd001/parts/0011345404/modules/273669854375461/lessons/3494350031/concepts/35019794250923#

In the solution code there is an invalid CSS rule on line 200 and 339.  

padding: 1.5em inherit;

inherit cannot be used for part of a shorthand declaration.  Should be either

 padding: inherit;

or each part should be done separately:

  padding: 1.5em;
  padding-left: inherit;
  padding-right: inherit;

**Comment by richardkalehoff** [comment]
I've updated the code to remove the `inherit` values. I set applied the following CSS, instead:

```css
padding-top: 1.5em;
padding-bottom: 1.5em;
```
