### ISSUE TITLE
Google Developer Challenge Scholarship: Front-End Web Dev

### ISSUE THREAD

**Issue by imracekmjkba** [udacity/fend-issues#90]
Lesson 19, 11. Quiz “Build a DOM (Family) Tree!”: there is a mistake in the code in the ANSWER.
Instead of /h3 is written /h2 for the names Hunter and Madison! It is just at the beginning of the video.

**Comment by richardkalehoff** [comment]
Thanks for posting! There actually is some text beneath the video that addresses the headings that start with an `<h3>` but incorrectly end with an `<h2>`.
