### ISSUE TITLE
Setting an Element's Attributes Example

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#91]
Version 7.0

https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/39d760cf-9593-420d-9a97-57bff31e29c1/concepts/3734dc32-5300-4ad9-96a8-be488f96a180

In the second phase of the core curriculum, 'Web Programming with JavaScript', lessen 20, 'Creating Content with JavaScript', and section 5 'Style Page Content', in subsection 'Setting an Element's Attributes', the given example is wrong. .setAttribute is a method and cannot be simply assign a value, while the example is like this:

mainHeading.setAttribute = 'color: blue; background-color: orange; font-size: 3.5em';

Should be mainHeading.setAttribute('style', 'color: blue; background-color: orange; font-size: 3.5em;');

Ticket #655168

**Comment by hbkwong** [comment]
Fixed! Updated the classroom and the script. Thanks @JessicaBettencourt

**Comment by JessicaBettencourt** [comment]
Awesome, thanks!
