### ISSUE TITLE
Create and Modify Properties Quiz Bug

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#92]
https://classroom.udacity.com/nanodegrees/nd001/parts/4942f4d7-a48d-4794-9eb0-404b3ed3cfe1/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/504843ae-ba16-4573-a859-94da7a7d1dd4/concepts/2bbcfed5-e683-431b-ace2-b67c091400d2

Core Curriculum Chapter 3, 'Exploring JS - Objects, Tools and Testing', in Lesson 7, 'Object in Depth', section 2, 'Create and Modify Properties', the question 5 of 6, 'Consider the following', is taking option 'apple' as the correct answer, whereas the real one is 'orange'. The popup after correct submission also tells that 'orange' is correct.

Ticket #662870

**Comment by hbkwong** [comment]
Fixed! @JessicaBettencourt
