### ISSUE TITLE
Callback Example Code

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#93]
https://classroom.udacity.com/nanodegrees/nd001/parts/4942f4d7-a48d-4794-9eb0-404b3ed3cfe1/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/fd2e70b8-84b4-4793-a89e-78a695ecf89d/concepts/435a5d87-0a67-4787-9096-5426e36f9a90

Core Curriculum, Chapter 3, 'Exploring JS - Objects, Tools and Testing', Lesson 8, 'Function at Runtime', Section 3, 'Callbacks', in subsection 'filter()', the example code is: 
const names = ['Andrew', 'Richard', 'Veronika'];

const shortNames = names.filter(function(name) { 
return name.length < 6; 
});

In the materials, shortNames is claimed to be ['Andrew'], but when running the code in console, it gave out an empty array, since Andrew also has a length >= 6. 
May need to either change Andrew to a shorter one or change 'return name.length < 6' to return 'name.length <= 6' to match the materials.

Ticket #663076

**Comment by hbkwong** [comment]
Fixed! I changed my name to 'David' so that it satisfies the existing conditions. Thanks @JessicaBettencourt
