### ISSUE TITLE
Select_Page_Elements_By_Class_Or_Tag_Issues

### ISSUE THREAD

**Issue by evestorm** [udacity/fend-issues#94]
> ![.getElementsByTagName()](https://user-images.githubusercontent.com/18142851/34661669-290f24a8-f486-11e7-9f6f-491b64d3f00e.png)
According to the context, I think "not `.getElementsByClassName()`" here is probably a typo for "and `.getElementsByTagName()`" .

> ![two](https://user-images.githubusercontent.com/18142851/34661717-7a0f0fa8-f486-11e7-8a4e-bc31c982bad9.png)
And "three" here is probably a typo for "two" ...

Link: [Web Programming with JavaScript -> The Document Object Model -> lesson 5](https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/74c2a096-61db-4302-9d65-6b7fa9b8c329/concepts/04d813ef-2bfc-4862-a4cc-38057d2a11c3)

**Comment by hbkwong** [comment]
@evestorm Fixed! Thank you all again for reporting this.
