### ISSUE TITLE
Phases of an Event Quiz

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#95]
https://classroom.udacity.com/nanodegrees/nd001/parts/3d3d1bdc-316b-46c2-bdcf-b713c82804da/modules/04eb38bd-45e1-4a58-98c8-1e6f1e770438/lessons/f270dbcf-eb43-4ce3-b7be-a74d26023496/concepts/5fdd280f-9bf8-4c13-b544-24cd9a4fb63e

Message from student:

document.body.addEventListener('click', function () { 
console.log('The document was clicked'); 
});

The console.log should state ('The body element was clicked') to match the responses of the quiz.

Ticket #668718

**Comment by hbkwong** [comment]
Fixed! Thanks @JessicaBettencourt
