### ISSUE TITLE
A Guide to Paths Typo

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#96]
This is in the free preview. 

https://classroom.udacity.com/courses/nd001-preview/lessons/7222405183/concepts/73276037150923

Lesson 3: HTML Syntax Problem Set A Guide to Paths 

"but it describes how to find to a file from a directory that is not the root directory."

should be...

"but it describes how to find a path to a file from a directory that is not the root directory."

Ticket #666603

**Comment by hbkwong** [comment]
Fixed!
